### ISSUE TITLE
Prefer Async.StartImmediateAsTask over Asyn.StartAsTask

### ISSUE THREAD

**Issue by OnurGumus** [fsbolero/Bolero#103]
https://github.com/fsbolero/Bolero/blob/fa37b7e30e4e2ba9cd02d6eaeb32d62971b5dbc7/src/Bolero/Components.fs#L170

For above line I think it's better to use Async.StartImmediateAsTask as it will hook into the current thread similar like async await.

P.S. I was the one who added this to F#

**Comment by Tarmil** [comment]
Good hint, thanks!
