### ISSUE TITLE
VS Code debugging and content path

### ISSUE THREAD

**Issue by OnurGumus** [fsbolero/Bolero#116]
When debugging the template app from VS Code it complains , it cannot find _Host as fallback.
I am not sure if this is a bolero issue, but I worked around it by
```

    [<EntryPoint>]
    let main args =
        Host.CreateDefaultBuilder(args)
            .ConfigureWebHostDefaults(fun webBuilder ->
               //only for VSCode debugging but will break other cases.
                webBuilder.UseContentRoot("../../../.") |> ignore
                webBuilder.UseStartup<Startup>() |> ignore
            ).Build().Run()
        0
```
Notice I changed the content root as the debugger from VS code uses the bin/debug folder as the content root, perhaps other solution is to make sure Page folder is copied to output.
As a side issue, template should use the above modern Host syntax rather than WebHost.

**Comment by OnurGumus** [comment]
Or alternatively adding this to proj file fixes it
```
<Content Include="Pages/_Host.cshtml" CopyToOutputDirectory="PreserveNewest"/>
```

**Comment by Tarmil** [comment]
I think a better solution would be to configure Code to run the project with the project folder as working directory by setting `"cwd"` in `.vscode/launch.json`.
