### ISSUE TITLE
New `bind` and re-render issue 0.11

### ISSUE THREAD

**Issue by brikken** [fsbolero/Bolero#119]
The new `bind.*` appears to have an issue with missing re-renders when the underlying value changes.

```F#
type Name = { first: string; last: string; }
type Model = { name: Name; }
type Message = | SetName of Name | ResetName
let init = { name = { first = ""; last = ""; }; }
let update model msg =
    match msg with
    | SetName name ->
        { model with name = name; },
        Cmd.none
    | ResetName ->
        { model with name = { first = ""; last = ""; }; },
        Cmd.none
let view model dispatch =
    concat [
        p [] [input [
            attr.placeholder "First name"
            bind.input.string model.name.first (fun first -> { model.name with first = first; } |> SetName |> dispatch)
        ]]
        p [] [input [
            attr.placeholder "Last name"
            bind.input.string model.name.last (fun last -> { model.name with last = last; } |> SetName |> dispatch)
        ]]
        p [] [text (sprintf "Entered name is %s %s" model.name.first model.name.last)]
        p [] [button [on.click (fun _ -> ResetName |> dispatch)] [text "Reset name"]]
    ]
```
**Expected**
When clicking "Reset name" (sending the `ResetName` message), the text boxes should be cleared.

**Actual**
The underlying model changes, as reflecting in the `<p>` printing the name, but the input boxes do not update their values

I've made two branches showcasing how the behaviour has changed from 0.10 to 0.11

https://github.com/brikken/Bolero/tree/twoway-bind-working (see [this view](https://github.com/brikken/Bolero/blob/twoway-bind-working/tests/Client/Binding.fs)) shows how the values in the `input`s match the model and how updates to the model, outside the event handler, also re-renders.

https://github.com/brikken/Bolero/tree/twoway-bind-error shows the same situation in 0.11, but notice how changes to the model outside the `input` event handler does not cause a re-render.

I've not attempted any debugging in Bolero code, but I assume it's related to the "tree comparison" algorithm in Blazor, that somehow optimizes this change away, causing a missing re-render.

**Comment by Tarmil** [comment]
Yes, I see the problem. `EventCallbackFactory.CreateBinder` creates an event handler that correctly converts from the input value to the model type, but we also need an `attr.value` that converts the other way using `BindConverter.FormatValue`, as they do for example [here](https://github.com/dotnet/aspnetcore/blob/3d178227da1572c19aeec2f5e826493088e72660/src/Components/Web/src/Forms/InputDate.cs#L30-L31).
