### ISSUE TITLE
Self hosted wasm

### ISSUE THREAD

**Issue by demamoh** [fsbolero/Bolero#122]
Hello,

Is there documentation on how to do self hosted webassembly with client side routing.

I am trying to figure out how to include the client side app as part of a bigger electron app. Any help is appreciated.

**Comment by Tarmil** [comment]
After building a Bolero app, the folder `src/*.Client/bin/Debug/netstandard2.1/dist` should contain all the static files you need. Just run the script `_framework/blazor.webassembly.js` from your page.

**Comment by demamoh** [comment]
Thanks @Tarmil, for the help.

I was also trying to do the same for the browser environment too. 

For future people, trying to go the self hosted route in the browser, you might run into  CORS problems, which does not exist in the electron environment. There are workarounds, but the best way it seems is to serve the files using a server, or you will run into Fetch errors.
