### ISSUE TITLE
debugging tips

### ISSUE THREAD

**Issue by ism** [fsbolero/Bolero#124]
I have couple of questions

1) How do you guys debug bolero app in VS Code? Any tips? It would be nice to add some docs regarding that.
2) Is bolero compatible with FSharp.Data JsonProvider ? I had a problem transferring JsonProvider<...>.Root from Server Side to Client.

Thanks!

**Comment by Tarmil** [comment]
1. One way to debug, if you're using the latest project template, would be to run the server project with your usual .NET Core debugger and pass `?server=true` to the url. This option is only available when compiling in debug mode and runs the app in Blazor server-side mode.

2. Bolero can use FSharp.Data.JsonProvider on the client side, as you can see [on Try F#](https://tryfsharp.fsbolero.io/?snippet=TP_Json). That being said, I haven't tried to transfer a provided value between the client and the server, so I'm not very surprised that it's not working.

**Comment by ism** [comment]
Thanks for tips!

I ended up transferring object as JSON string from the server side, de-serializing it on client side using FSharp.Data. My guess it is not related Bolero itself, so i am closing the thread.
