### ISSUE TITLE
Question: purely client-side bolero

### ISSUE THREAD

**Issue by nojaf** [fsbolero/Bolero#128]
Hello, I'm considering playing around with Bolero and would like to port an existing application.
I have a couple of questions as I'm not entirely sure everything I have in mind is possible.

* Can I create a pure client-side bolero application without any server involved? Any samples on this?
* What dlls can be used when using Bolero in the browser? This might be a more general Blazor question but I would like to know if it is possible to use [FSharp.Compiler.Service](https://www.nuget.org/packages/FSharp.Compiler.Service/) package via WASM? It is netstandard2.0 but I don't know if that is enough.
* What is the interopt story when working with Blazor? Could I combine a Bolero application with the [Monaco editor](https://microsoft.github.io/monaco-editor/) for example?

**Comment by granicz** [comment]
To answer all of these in one go: there is a "Try F# in WebAssembly" button on the [Bolero home page](https://fsbolero.io) and its sources are [here](https://github.com/fsbolero/TryFSharpOnWasm). It does not yet use Monaco, so PRs are welcome. Also, updating FCS in that sample has been recently discussed in the [Bolero Gitter channel](https://gitter.im/fsbolero/community), you are welcome to join and discuss further.

**Comment by nojaf** [comment]
So you folks forked FCS into Bolero.FSharp.Compiler.Service and the regular version cannot be used as is?

**Comment by kamcma** [comment]
Not an official sample, but I have a small client-side-only Bolero sample [here](https://github.com/kamcma/bolero-minimal-sample). (It's wired up for the VS Code Remote Container stuff, but you can ignore that.) It has the Blazor dev server as a development dependency, because you need something to serve the static assets, but when building for deployment, you would just copy publish output to where you're going to serve it from.

**Comment by Tarmil** [comment]
> So you folks forked FCS into Bolero.FSharp.Compiler.Service and the regular version cannot be used as is?

Yes, but only due to some minor things in FCS such as calls to System.Diagnostics not working in Blazor. The changes are *much* less extensive than those in Fable's fork, for example.

**Comment by nojaf** [comment]
Ok, thank you for this response.
