### ISSUE TITLE
Putting everything together: Mixing HTML in F# with Templates, Elmish and other Features

### ISSUE THREAD

**Issue by sirinath** [fsbolero/Bolero#130]
Is it possible to add to documentation on how to mix and match Mixing HTML in F# with Templates and Elmish where certain parts are written in HTML in F# and others in templates using the Elmish Architecture? This is essentially putting everything together and how different features interact.

**Comment by Tarmil** [comment]
I suppose it could be made more explicit in the docs, but they're the same type `Node`, so you can just use either syntax wherever child nodes are expected.

```fsharp
type Tpl = Template<"""<div>${Body}</div>""">

/// Use a template inside F#:
div [] [
    Tpl().Elt()
]

/// Use F# inside a template:
Tpl()
    .Body(div [] [text "Hello!"])
    .Elt()
```
