### ISSUE TITLE
Interacting with JS and Frameworks

### ISSUE THREAD

**Issue by sirinath** [fsbolero/Bolero#131]
For someone new to and just checking out this framework, it is not apparent how to interact with JS and other frameworks. Maybe this needs documentation.

JS interaction can be from or with HTML in F#, Templates, Elmish and other Features

**Comment by OnurGumus** [comment]
@sirinath , Bolero is just a Blazor component! Anything applies to Blazor, applies to Bolero as well. You can define methods on your program class and have it called from JS or inject JSRuntime. Program class is just a regular Blazor component.

**Comment by Tarmil** [comment]
Indeed. In fact, `ProgramComponent` already has an injected runtime, so you can use `this.JSRuntime`.

**Comment by Tarmil** [comment]
I added a section about this in the documentation: https://fsbolero.io/docs/Blazor#javascript-interoperability

**Comment by sirinath** [comment]
Thanks.

**Comment by pmd3d** [comment]
Thanks.

**Comment by zakaluka** [comment]
My apologies for asking a very naive question, but is this the same technique that I should use to add Javascript "widgets" into the view?  

E.g., if I wanted to use the [bpmn-js](https://bpmn.io/toolkit/bpmn-js/) library as part of a page, would I use the IJSRuntime to run the following JavaScript within the `view` function?

```javascript
  var viewer = new BpmnJS({ container: 'body' });

  viewer.importXML(bpmnXML, function(err) {

    if (err) {
      console.log('error rendering', err);
    } else {
      console.log('we are good!');
    }
  });
```

**Comment by sebfia** [comment]
Can you add documentation on how to add third party components to a Bolero app, please!

**Comment by OnurGumus** [comment]
@sebfia here's a sample project using leaflet
https://github.com/OnurGumus/FBlazorShop

**Comment by sebfia** [comment]
Thank you for the fast reply!

**Comment by sebfia** [comment]
Looking at the project (which is very nicely done) I found the leaflet to be a javascript component. Is there any guidance on how to proceed with Blazor components (I am specifically looking at binding eg. Syncfusion Blazor components into a bolero app)?

**Comment by Tarmil** [comment]
@sebfia These appear to be simple components, so you can use them in Bolero [using `comp`](https://fsbolero.io/docs/HTML#components). For example, this:

```razor
<SfTextBox CssClass="e-filled" Placeholder="Filled" FloatLabelType="@FloatLabelType.Auto"></SfTextBox>
```

would be called like this:

```fsharp
comp<SfTextBox> ["CssClass" => "e-filled"; "Placeholder" => "Filled"; "FloatLabelType" => FloatLabelType.Auto] []
```

**Comment by sebfia** [comment]
Ah, now I get it.  Thank you
