### ISSUE TITLE
PSA: Template only works with latest .NET Core SDK (3.1.201)

### ISSUE THREAD

**Issue by brikken** [fsbolero/Bolero#133]
If you - like me - was lagging behind with just 3.1.0, you get a hard-to-understand build error.

Upgrading to latest Visual Studio or .NET Core SDK solves the problem.

**Comment by Tarmil** [comment]
Yes, if I'm not mistaken it works with version 3.1.2 of the netcore runtime, so SDK version 3.1.102 or 3.1.200.

**Comment by rbrus** [comment]
Not sure what is going on but last week everything was fine, this week I have installed VS Preview, and possibly updated sdk and VS (not preview) and now I am not able to run fsbolero. I spend last two hours on uninstalling and reinstalling VSs and SDKs but nothing help. Version 3.1.200 also doesn't work.

![image](https://user-images.githubusercontent.com/6479266/87506283-374fd300-c66b-11ea-9a06-d09d9ab148a4.png)

Any ideas what could be wrong or how to debug the issue?

Thanks in advance!

**Comment by Tarmil** [comment]
Well, now that Bolero references Blazor 3.2, the minimal SDK required is actually 3.1.301.

I see that [they released Blazor packages 18 hours ago](https://www.nuget.org/packages/microsoft.aspnetcore.components.webassembly), maybe that's related?

**Comment by rbrus** [comment]
I think this might be it.

I have changed references in the project file to:
	  <PackageReference Include="Bolero" Version="0.13.23" />
	  <PackageReference Include="Bolero.Build" Version="0.13.23" />
	  <PackageReference Include="Bolero.HotReload" Version="0.13.8" />
	  <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Build" Version="3.2.0" />
	  <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="3.2.0" />

And now it works, finally.

**Comment by rbrus** [comment]
Hmm, now I am running on the correct versions and using client-server (template) project - not client only, and I am receving the same issue:

![image](https://user-images.githubusercontent.com/6479266/87658040-ef5ca900-c75b-11ea-8159-40a75edfff73.png)

**Comment by Happypig375** [comment]
What is PSA?

**Comment by panesofglass** [comment]
@Happypig375 Public Service Announcement

**Comment by Happypig375** [comment]
Thanks

**Comment by Tarmil** [comment]
@rbrus The issue is caused by Microsoft.AspNetCore.Components.WebAssembly.Build 3.2.1. If you set just this package to 3.2.0, the problem should go away.
