### ISSUE TITLE
Added to fsharp.org

### ISSUE THREAD

**Issue by dsyme** [fsbolero/Bolero#140]
Just to let you know Bolero has been added as an option for building web apps on http://fsharp.org

https://fsharp.org/use/web-apps/

It's also listed in the web guide (it was there already)

Thanks @granicz for suggesting this.  Please make sure the information is kept up-to-date and that your getting-started quickstart is as good and simple as possible.

**Comment by Tarmil** [comment]
Awesome 👍 And good timing, I'm in the middle of updating the try online site to the latest versions of FCS and Bolero.

**Comment by granicz** [comment]
Cool, thanks!
