### ISSUE TITLE
How to use MatBlazor, ant design for blazor etc?

### ISSUE THREAD

**Issue by albertwoo** [fsbolero/Bolero#142]
I am trying the cool library but when I try to use third party library I cannot find an elegant way to use it. For example MatBlazor. Any guide for this?

**Comment by zakaluka** [comment]
If it's just a Blazor component, should it be done using `comp`?  Doc: https://fsbolero.io/docs/HTML#components

**Comment by Tarmil** [comment]
To use third-party components, you can use the `comp` function, for example the following Blazor:

```razor
<MatButton Link="https://github.com/BlazorComponents/MatBlazor">
    Hello, world!
</MatButton>
```

becomes in Bolero:

```fsharp
comp<MatButton>
  [ "Link" => "https://github.com/BlazorComponents/MatBlazor" ]
  [ text "Hello, world!" ]
```

Unfortunately event handlers for Blazor components, like MatBlazor's `OnClick`, are currently tedious to set up, but I'm working to improve it and it should be much better soon. For now, the following Blazor:

```razor
<MatButton OnClick="@RunOnClick">
    Hello, world!
</MatButton>

@code
{
    public void RunOnClick(MouseEventArgs e)
    {
        JsRuntime.InvokeAsync<object>("window.alert", "Test");
    }
}
```

becomes in Bolero:

```fsharp
let OnClick (f: MouseEventArgs -> unit) =
    ExplicitAttr(Func<_,_,_,_>(fun builder sequence receiver ->
        builder.AddAttribute(sequence, "OnClick",
            EventCallback.Factory.Create(receiver, Action<_>(f)))
        sequence + 1))

comp<MatButton>
  [ OnClick (fun _ ->
        this.JsRuntime.InvokeAsync<object>("window.alert", "Test") |> ignore) ]
  [ text "Hello, world!" ]
```

In the upcoming release it should simply be:

```fsharp
comp<MatButton>
  [ attr.callback "OnClick" (fun _ ->
        this.JsRuntime.InvokeAsync<object>("window.alert", "Test") |> ignore) ]
  [ text "Hello, world!" ]
```

**Comment by albertwoo** [comment]
But this way is not type safe and un-productive. Do we have other cool way for this? Or any type providers for this stuff?

**Comment by albertwoo** [comment]
If we can have this (clean and easy use of apis or maybe like feliz) and hot reload (not the template one, the fable + react like hot reload) then things gonna be cooler than fable + react.

**Comment by Tarmil** [comment]
Unfortunately a type provider would need to receive the type `MatButton` as parameter, to be able to analyze its attributes, but that is currently not possible. [In a future version of F#, hopefully!](https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1023-type-providers-generate-types-from-types.md)

**Comment by albertwoo** [comment]
Do you think https://github.com/MoiraeSoftware/myriad is helpful for this purpose?

**Comment by NickDarvey** [comment]
I feel I have a related question about using it with Bolero with other libraries, and it's brief so I thought I'd add it here.

If I have a JS library that expects you to use it like:
```js
element.bulmaCalendar.on('select', datepicker => {
  console.log(datepicker.data.value());
});
```
are there any helpers in Bolero to help me get at that value?

Otherwise, should I just be building a Component and following [the guidance about calling .NET code from JavasScript](https://docs.microsoft.com/en-us/aspnet/core/blazor/call-dotnet-from-javascript?view=aspnetcore-3.1#instance-method-call)?

**Comment by Tarmil** [comment]
> In the upcoming release it should simply be:
> 
> ```fsharp
> comp<MatButton>
>   [ attr.callback "OnClick" (fun _ ->
>         this.JsRuntime.InvokeAsync<object>("window.alert", "Test") |> ignore) ]
>   [ text "Hello, world!" ]
> ```

This has just been released in v0.13.

**Comment by ericdes** [comment]
> > In the upcoming release it should simply be:
> > ```fsharp
> > comp<MatButton>
> >   [ attr.callback "OnClick" (fun _ ->
> >         this.JsRuntime.InvokeAsync<object>("window.alert", "Test") |> ignore) ]
> >   [ text "Hello, world!" ]
> > ```
> 
> This has just been released in v0.13.

Hello, 

The same code using the [Mudblazor components](https://mudblazor.com/components/button) 

```
                comp<MudButton> [ attr.callback "OnClick" (fun _ -> dispatch DbSave) ] [
                    text "Save"
                ]
```
 leads to this critical error:

> crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
>       Unhandled exception rendering component: Unable to set property 'OnClick' on object of type 'MudBlazor.MudButton'. The error was: Specified cast is not valid.


The code of the MudButton looks pretty much the same though, with the event invoked async:

```
        /// <summary>
        /// Button click event.
        /// </summary>
        [Parameter] public EventCallback<MouseEventArgs> OnClick { get; set; }
```

Would you have any hints as to how debug that problem?

**Comment by ericdes** [comment]
I confirm, this is the right way:

```
                comp<MudButton> [ attr.callback<MouseEventArgs> "OnClick" (fun _ -> dispatch DbSave) ] [
                    text "Save"
                ]
```
Thank you!

**Comment by albertwoo** [comment]
Currently I am trying to make an experimetal cli tool for this. So far it works good:
https://funblazor.slaveoftime.fun/cli-usage
https://github.com/slaveOftime/Fun.Blazor

I will close my issue now.
