### ISSUE TITLE
ElmishComponent and invoking JavaScript

### ISSUE THREAD

**Issue by NickDarvey** [fsbolero/Bolero#145]
I have an `ElmishComponent` and depending on something determined in `View` I might want to invoke some JavaScript to take the focus.

```fsharp
  type Component() =
    inherit ElmishComponent<Model, string>()

    [<Inject>]
    member val JSRuntime = Unchecked.defaultof<IJSRuntime> with get, set

    override this.ShouldRender (prev, next) = prev.value <> next.value

    override this.View model dispatch =
      let input =
        cond model.value <| function
        | ValueSome v -> input [
          attr.id   model.props.id
          attr.name model.props.id
          attr.``type`` "text"
          bind.change.string v (fun e -> dispatch e) ]
        | ValueNone   -> button [
          attr.name model.props.id
          attr.``type`` "button"
          on.click (fun _ -> dispatch "Custom") ] [ text "Default" ]
```

And I need to invoke this somewhere after the `ValueSome v -> ...` path happens
```fsharp
js.InvokeVoidAsync("extensions.focusOn", props.id).AsTask()
```

My thoughts were to do invoke it in `OnAfterRenderAsync`, however I don't know how to figure out that the change (from `ValueNone` to `ValueSome`) has happened there.

I see there's an `OldModel` which I guess I could have used to check if I had just changed but it's (understandably) internal. Is there another way for me to figure out it's time to invoke my function?

In the meantime I'm bubbling up a message via `dispatch` and having the parent invoke the function during it's `update` function using a `Cmd`. (The reason I'd like to avoid this is this behaviour should be tied to this component, it's inherent to how it works, the parent should be oblivious to it (well, in my opinion anyway.)

**Comment by Tarmil** [comment]
> The reason I'd like to avoid this is this behaviour should be tied to this component, it's inherent to how it works, the parent should be oblivious to it (well, in my opinion anyway.

The canonical way to deal with a component that has its own internal behavior would be to give it its own message type and update function, something like this:

```fsharp
type ComponentMessage =
    | SetValue of string
    | Focus
```

The parent then doesn't need to know how it's handled, it just calls the child update function.

That being said, I suppose it would make sense to add an overloaded `OnAfterRenderAsync(oldModel, newModel)` for such simple cases.

**Comment by NickDarvey** [comment]
I'm also happy to give the component its own message type and update function too, but I wasn't sure what should invoke the update func and handle its commands  (because I'm wanting to invoke JavaScript, I need something to await the Task for me). Does it need to be wired all the way up the hierarchy? In which case, that's what I have now, but the focus changing seemed like internal behaviour. Maybe I just need to think about it differently...

**Comment by Tarmil** [comment]
Yeah, in general in MVU internal behavior isn't completely invisible to a parent component. Instead it's the child component telling its parent "I have a message type and an update function, don't worry about what they do, just wrap my message type in a case of yours and call my update function when handling that case". [Something like this.](https://elmish.github.io/elmish/parent-child.html)

**Comment by NickDarvey** [comment]
Ok, that makes sense. Thanks @Tarmil
