### ISSUE TITLE
Any plans for a final release?

### ISSUE THREAD

**Issue by Arshia001** [fsbolero/Bolero#147]
Since the stable version of Blazor was just released, I'm wondering if there are any plans for a stable release of Bolero?

**Comment by Tarmil** [comment]
Very soon :) The master branch is already referencing the released Blazor 3.2.0.

**Comment by Tarmil** [comment]
[Done 🙂](https://github.com/fsbolero/Bolero/releases)

**Comment by Arshia001** [comment]
Wow, that was quick 🙂
