### ISSUE TITLE
Custom router gets stuck in a SetRoute loop on first navigation

### ISSUE THREAD

**Issue by NickDarvey** [fsbolero/Bolero#151]
I'm having an issue with implementing a custom router where it `setRoute` is called infinitely.

``` fsharp
let router : Router<Page, Model, Message> = {
  getEndPoint = fun m -> m.page
  setRoute = fun path ->
      match path.Trim('/').Split('/') with
      | [||]     -> Some <| Home
      | [|"c" |] -> Some <| Counter
      | _ -> None
      |> Option.map SetPage
  getRoute = function
      | Page.Home    -> "/"
      | Page.Counter -> "/c"
}
```
https://github.com/NickDarvey/bolero-custom-router/blob/0bfea305481d412cc4ab9f2ae25e2bd85f8c8c49/src/RoutingPlz.Client/Main.fs#L98-L111

## Repro
1. Clone [this repo](https://github.com/NickDarvey/bolero-custom-router)
2. Run app
3. Click 'counter' link

## Expected
Navigates to counter page via an invocation of `setRoute`.

## Actual
`setRoute` is called infinitely.

## System info
- The repro project a stripped down version of the `bolero-app` template.
- I (believe I) followed the steps [in the docs](https://fsbolero.io/docs/Routing#custom-router) to create my router.

This is at the top of the call stack:
   ```
   Bolero.dll!<StartupCode$Bolero>.$Components.OnLocationChanged@146<RoutingPlz.Client.Main.Model, RoutingPlz.Client.Main.Message>.Invoke(Bolero.IRouter<RoutingPlz.Client.Main.Model, RoutingPlz.Client.Main.Message> router)
   ```
 
 
 https://github.com/fsbolero/Bolero/blob/4b2e042e059ddf983d78dde7582a6cc1c2cbf365/src/Bolero/Components.fs#L145-L149

**Comment by Tarmil** [comment]
Ah, I found the problem. In the custom router, `getRoute` actually needs to return relative paths, ie without the initial `/`. That's doubly wrong: it's not intuitive, and it contradicts the documentation! I'll fix it so that either absolute or relative paths can be used.

**Comment by NickDarvey** [comment]
Fantastic, thank you @Tarmil
