### ISSUE TITLE
DateTimeOffset is adjusted to universal time during JSON decoding with remoting

### ISSUE THREAD

**Issue by NickDarvey** [fsbolero/Bolero#154]
I'm having an issue where a DateTimeOffset I send is losing its offset when it reaches the server (using remoting). I can see that it is being POSTed with the offset, but my server method sees 00:00.

## Repro
1. Checkout [adapted example](https://github.com/NickDarvey/Bolero/commit/db6c20a5f1c046853390e8f439b2443fa0008bd6)
1. Put a breakpoint in [the server implementation](https://github.com/NickDarvey/Bolero/commit/db6c20a5f1c046853390e8f439b2443fa0008bd6#diff-e7675663e5363ee14c459c0c7da2ee98R71)
1. Run `Remoting.Server`

## Expected
DateTimeOffset contains offset based on local machine's timezone.

## Actual
DateTimeOffset is shifted to universal (+00:00).

## Additional info
This does not occur when in server mode or during prerendering. It looks like the JSON decoding is configured to shift it to universal:
https://github.com/fsbolero/Bolero/blob/fc9e34622a309b63d56c41195777f7d78023c2a3/src/Bolero/Json.fs#L1107

used in:

https://github.com/fsbolero/Bolero/blob/fc9e34622a309b63d56c41195777f7d78023c2a3/src/Bolero/Json.fs#L1181-L1191

I feel like this might be a mistake as it behaves differently when in server mode (I guess because no JSON'ing is happening). It could be solved by using the default datetime style for decoding, but fixing this might break for people relying on this behaviour. I had a brief look but wasn't sure how to (neatly) weave it in as a configuration option.

**Comment by Tarmil** [comment]
This seems wrong indeed.

To be honest, I've been thinking about removing this entire JSON serializer (which is adapted from WebSharper's) and switching to System.Text.Json, which is already used by other parts of Blazor.

**Comment by NickDarvey** [comment]
(Will be) fixed by #159, #160
