### ISSUE TITLE
Repository of examples?

### ISSUE THREAD

**Issue by deviousasti** [fsbolero/Bolero#156]
Is there currently a repository of examples.
I currently see three - the Try Bolero, TodoMVC and the Bolero template, each in its own repository.

Are there any plans to make a mono-repo for samples?
Like https://github.com/Microsoft/VSSDK-Extensibility-Samples

I've made a sample to test out Async, GC, frame-rate and cost of updates.
Source here:
https://github.com/deviousasti/gameoflife-wasm

Hosted here:
https://asti.dynz.net/gameoflife-wasm/

If there's a plan for a samples repo, I'd love to contribute this and a few minor ones.

**Comment by deviousasti** [comment]
Will submit a PR when a gallery is added to Bolero. Closing.

**Comment by granicz** [comment]
@deviousasti Sorry for the delay. Just added a new [awesome-bolero](https://github.com/fsbolero/awesome-bolero) repo for collecting Bolero resources, feel free to submit a PR to it with examples. I don't think we are planning a separate org for examples, it's best to keep things flowing freely.
