### ISSUE TITLE
Switch to System.Text.Json

### ISSUE THREAD

**Issue by Tarmil** [fsbolero/Bolero#159]
Currently JSON serialization for remote calls is done using a custom serializer adapted from WebSharper. I think it would be better to switch to System.Text.Json (combined with [FSharp.SystemTextJson](https://github.com/Tarmil/FSharp.SystemTextJson)) for several reasons:

* It would fix issues such as #154.
* System.Text.Json is included in the bundle regardless, because it is used for js interop, so we would just replace the custom serializer with FSharp.SystemTextJson, which is probably smaller.
* FSharp.SystemTextJson has more customization options, in particular surrounding unions and option values.

**Comment by granicz** [comment]
Given that we use a lot of records, how would the above compare performance-wise?

**Comment by Tarmil** [comment]
With [this simple benchmark](https://gist.github.com/Tarmil/88634832d0496be34a820123063e6e6e) I get the following results:

|         Method |     Mean |    Error |  StdDev |
|--------------- |---------:|---------:|--------:|
|     BoleroJson | 936.6 ns |  9.17 ns | 8.12 ns |
| SystemTextJson | 747.3 ns | 10.19 ns | 9.53 ns |

**Comment by Tarmil** [comment]
And [for a simple union](https://gist.github.com/Tarmil/e7d0b13f5ad9f72252d4e2d86815775b):

|         Method |     Mean |     Error |    StdDev |
|--------------- |---------:|----------:|----------:|
|     BoleroJson | 2.097 us | 0.0171 us | 0.0160 us |
| SystemTextJson | 1.380 us | 0.0272 us | 0.0291 us |

**Comment by granicz** [comment]
Are these with `FSharp.SystemTextJson`? The numbers look great!

**Comment by Tarmil** [comment]
Yep. Deserialization is closer (and in fact slightly worse for records):

|                            Method |       Mean |    Error |   StdDev |
|---------------------------------- |-----------:|---------:|---------:|
|       Serialize_Record_BoleroJson |   894.2 ns |  3.81 ns |  3.18 ns |
|   Serialize_Record_SystemTextJson |   747.3 ns |  8.42 ns |  7.88 ns |
|        Serialize_Union_BoleroJson | 2,072.2 ns | 17.75 ns | 16.60 ns |
|    Serialize_Union_SystemTextJson | 1,278.8 ns | 20.98 ns | 18.60 ns |
|     Deserialize_Record_BoleroJson | 1,493.3 ns | 21.25 ns | 19.88 ns |
| Deserialize_Record_SystemTextJson | 1,665.3 ns | 14.75 ns | 13.80 ns |
|      Deserialize_Union_BoleroJson | 1,842.0 ns | 12.36 ns | 10.95 ns |
|  Deserialize_Union_SystemTextJson | 1,605.5 ns | 17.03 ns | 15.93 ns |

**Comment by granicz** [comment]
Nice. Any idea what could be the bottleneck for record deserialization?

**Comment by Tarmil** [comment]
Not yet, but I can take a look.

I have an experimental branch on FSharp.SystemTextJson that uses Reflection.Emit instead of FSharp.Reflection, it was faster, but I haven't updated it in quite a while and it would probably have to be used only on the server side anyway.
