### ISSUE TITLE
wwwroot/index.html is cached

### ISSUE THREAD

**Issue by DejanMilicic** [fsbolero/Bolero#161]
I am trying to change index.html which contains references to CSS files, etc.  
Seems like it is heavily cached somewhere since I cannot change it - I always end up with an original version.  
I tried everything - renaming index.html to index2.html, deleting obj and bin files, etc, but I keep getting
served the same HTML I started with when I scaffolded solution.

**Comment by rusanov-vladimir** [comment]
Are you aware that there are 2 `index.html` files in the generated solution: one in client project and one in server project? Maybe you are changing the wrong one?

**Comment by Tarmil** [comment]
I am actually wondering whether I should remove the one in the Client project, and only include it when the project is created with `--server=false`. When running the server, the served page is always from `Pages/_Host.cshtml`.

**Comment by DejanMilicic** [comment]
> Are you aware that there are 2 `index.html` files in the generated solution: one in client project and one in server project? Maybe you are changing the wrong one?

Precisely what happened.  My bad.

@Tarmil that would be a good move, since it would prevent stupid errors like one I had

**Comment by Tarmil** [comment]
Oh, actually I realize that I have already implemented that, except [I mistyped it as "index.json" for some reason...](https://github.com/fsbolero/Template/blob/f0b58bce8c7ce6360944827effa6d321dc4f58f4/content/application/.template.config/template.json#L130-L135)
