### ISSUE TITLE
Cascading Values/Parameters

### ISSUE THREAD

**Issue by AngelMunoz** [fsbolero/Bolero#165]
First of all amazing work, I'm really loving it!

I have a question, Is there support for Cascading Values?

I have been learning (I want to believe properly this time)  bolero and I know Parameters work
I was wondering if there is CascadingValues support since I see no mention about it on the Blazor features section in the docs
https://fsbolero.io/docs/Blazor

**Comment by Tarmil** [comment]
I think it should work out of the box using `comp`:

```fsharp
type FooComponent() =
    inherit Component()

    [<CascadingParameter>]
    member val MeaningOfLife = 0 with get, set

    override this.Render() =
        concat [
            h1 [] [text "Foo component"]
            p [] [textf "The meaning of life is %i" this.MeaningOfLife]
        ]

comp<CascadingValue> ["Value" => 42] [
    comp<FooComponent> [] []
]
```

**Comment by AngelMunoz** [comment]
Ah, you are right I just checked it, it flew completely over my head.
Mind if I add something about them to the docs?
