### ISSUE TITLE
Hooking into disposal of ProgramComponent

### ISSUE THREAD

**Issue by NickDarvey** [fsbolero/Bolero#166]
**Issue**
If I understand explicit interface implementations correctly (a big 'if') there's no way for me to hook into `ProgramComponent`'s disposal right now.

https://github.com/fsbolero/Bolero/blob/397a761ba2efc9f4a7770c035b4c65d818467743/src/Bolero/Components.fs#L219-L222

Would it be possible to expose a way register things for disposal?

**Use case**
My use case is disposing a timer used via a Elmish sub as described by @Tarmil in [this issue](https://github.com/fsbolero/Bolero/issues/41#issuecomment-483571735). If it's not wired for disposal _and_ you are using server prerendering that timer will keep ticking on the server.

**Workaround**
I think for now I might be able to copy and tweak `ProgramComponent` to meet my needs. Or, perhaps I create a (visually empty) Component to hold these resources and pass it through to my view method so it'll appear in the render tree and be disposed by the runtime.

**Comment by NickDarvey** [comment]
I ended up implementing the second workaround, a Component to hold the subscriptions. I've run into another issue, or otherwise I've totally [XY](https://en.wikipedia.org/wiki/XY_problem)'ed here...

[In this first commit](https://github.com/NickDarvey/Prerendering/commit/fc06d721076748e3c899d65697a1154fa8c65f42), you can see me implement the `SubscribeComponent` to hold the subscription and adjust the root path to point to the `Counter` page so it's the one that loads first and gets pre-rendered.
If I run this, I can see the counter incrementing as expected, but no logs in the browser console, and no logs in the server console (i.e. except for the occasional: `trce: Microsoft.AspNetCore.SignalR.HubConnectionContext[3] Sent a ping message to the client.`).

In [this second commit](https://github.com/NickDarvey/Prerendering/commit/789c8f578c10e6b743a8b7f798bc653b185b6254), I switch the root path back to `Home` but add a redirect: a `Cmd` with `SetPage` to `Counter`.
If I run this, I can see the counter incrementing as expected, and at every interval I can see my `Interval!` logged in the browser console, and I can see `Interval!` logged in the server console along with `dbug: Microsoft.AspNetCore.Components.Server.Circuits.RemoteNavigationManager[1] Requesting navigation to URI counter with forceLoad=False`.
If I navigate away, say to `/data`, I no longer see the timer ticking in the browser console, but can still see the timer continuing to tick on the server (with the same logged `Interval!` and `dbug: ... Requesting navigation to URI counter...`

In _both_ cases I can see the prerender with the SubscribeComponent occuring once when 
```
info: Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker[3]
      Route matched with {page = "/_Host"}. Executing page /_Host
...
dbug: Microsoft.AspNetCore.Components.RenderTree.Renderer[2]
      Initializing root component 0 (Prerendering.Client.Main+MyApp)
dbug: Microsoft.AspNetCore.Components.RenderTree.Renderer[3]
      Rendering component 0 of type Prerendering.Client.Main+MyApp
dbug: Microsoft.AspNetCore.Components.RenderTree.Renderer[1]
      Initializing component 1 (Bolero.Html+SubscribeComponent) as child of 0 (Prerendering.Client.Main+MyApp)
dbug: Microsoft.AspNetCore.Components.RenderTree.Renderer[3]
      Rendering component 1 of type Bolero.Html+SubscribeComponent
dbug: Microsoft.AspNetCore.Components.RenderTree.Renderer[3]
      Rendering component 0 of type Prerendering.Client.Main+MyApp
dbug: Microsoft.AspNetCore.Components.RenderTree.Renderer[3]
      Rendering component 1 of type Bolero.Html+SubscribeComponent
dbug: Microsoft.AspNetCore.Components.RenderTree.Renderer[4]
      Disposing component 0 of type Prerendering.Client.Main+MyApp
dbug: Microsoft.AspNetCore.Components.RenderTree.Renderer[4]
      Disposing component 1 of type Bolero.Html+SubscribeComponent
Dispose!
```

## Repro
1. Clone https://github.com/NickDarvey/Prerendering/commit/789c8f578c10e6b743a8b7f798bc653b185b6254
1. Run

## Expected
Timer fires on client.

## Actual
Timer fires on server and client, and does not stop firing on server.

## Workarounds
* [Tested] Remove client-side redirect (`Cmd.ofMsg <| SetPage p`)
* [Untested] Find a way to defer client-side redirect till after prerender ([potential method described here](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-3.1#detect-when-the-app-is-prerendering))
* [Untested] Find a way to defer subscription till after prerender

**Comment by Tarmil** [comment]
I think we need to implement a proper [Dispose pattern](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose#implement-the-dispose-pattern) on ProgramComponent to handle situations like this.

**Comment by Tarmil** [comment]
I've looked into this some more, and the real problem is that we shouldn't start the subscriptions during prerender in the first place. If Elmish provided a way to [do the first render, and delay starting the program loop](https://github.com/elmish/elmish/issues/210), then we could do the first render in `OnInitialized`, start the program in the first `OnAfterRenderAsync`, and prerender would be doing only what it needs to do.

**Comment by NickDarvey** [comment]
An even better fix! Thanks @Tarmil
