### ISSUE TITLE
Invalid href value when using router

### ISSUE THREAD

**Issue by Liminiens** [fsbolero/Bolero#17]
If we pass `/` as an endpoint value then it would be trimmed and the resulting `href` attribute would be invalid.

```
type ApplicationPage =
    | [<EndPoint "/">]
      Home
```

```
a [router.HRef Home] [...]
```

results in 

```
<a href="">...</a>
```

when it should be

```
<a href="/">...</a>
```

**Comment by granicz** [comment]
`/` refers to the root of the application, and not the root of the domain. In what way is `""` invalid?

**Comment by Liminiens** [comment]
How do I route to the domain root then? Right now it's not [possible](https://github.com/fsbolero/Bolero/blob/master/src/Bolero/Router.fs#L72) if I understand correctly. On href attr I stand corrected, I thought that spec disallowed it :)

**Comment by Liminiens** [comment]
Oops. Looks like the issue was in missing `base` tag in my `index.html`. I'll close the issue then. Sorry for troubling.

**Comment by Tarmil** [comment]
This is indeed a stumbling point. I created #18 to add it to the documentation.
