### ISSUE TITLE
template for standalone app with Azure Active Directory B2C

### ISSUE THREAD

**Issue by Ma3yTa** [fsbolero/Bolero#173]
please provide a template for standalone app with Azure Active Directory B2C
https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-azure-active-directory-b2c?view=aspnetcore-3.1

**Comment by anderslm** [comment]
@Ma3yTa 
I have created a simple example of how to use MSAL.js: https://github.com/anderslm/fsharp-bolero-azure-ad

Maybe I'll do one using `Microsoft.Authentication.WebAssembly.Msal` as well, but this should help get you started.
