### ISSUE TITLE
Can't get dependency from container

### ISSUE THREAD

**Issue by ittennull** [fsbolero/Bolero#176]
Here is a demo repository https://gitlab.com/ittennull/bolero_di_issue/
First commit is the standard template as is, second commit adds an interface, registers it and tries to inject it:
```fsharp
type ISomething =
    abstract member Foo: unit -> unit
    
type Something() =
    interface ISomething with
        member _.Foo() = ()

type MyApp() =
    inherit ProgramComponent<Model, Message>()
    
    [<Inject>]
    member val Something = Unchecked.defaultof<ISomething> with get,set
```

```fsharp
let Main args =
        let builder = WebAssemblyHostBuilder.CreateDefault(args)
        builder.Services.AddSingleton<ISomething, Something>() |> ignore
        ...
```

I get 
" An unhandled exception was thrown by the application.
System.InvalidOperationException: Cannot provide a value for property 'Something' on type 'BoleroHostedApplication1.Client.Main+MyApp'. There is no registered service of type 'BoleroHostedApplication1.Client.Main+ISomething'"

I tried the same thing with blazor wasm project in C# - worked fine

Any ideas?

**Comment by NickDarvey** [comment]
Are you using prerendering?

```
services.AddBoleroHost(prerendered = ?)
```
(I think it's true by default.)

You'll probably need to register the service in your server project's `Startup.fs` too.

**Comment by ittennull** [comment]
I already tried both modes, I also thought it might be connected to the wasm mode but no - the result is the same

**Comment by ittennull** [comment]
It also works when I get right after adding it to the container:
```fsharp
let Main args =
        let builder = WebAssemblyHostBuilder.CreateDefault(args)
        
        // add
        builder.Services.AddSingleton<ISomething, Something>() |> ignore
        
        builder.RootComponents.Add<Main.MyApp>("#main")
        builder.Services.AddRemoting(builder.HostEnvironment) |> ignore
        
        // get
        let host = builder.Build()
        let noExceptionsHere = host.Services.GetRequiredService<ISomething>()
        
        host.RunAsync() |> ignore
```

**Comment by NickDarvey** [comment]
Ahh ok.

Perhaps because you're asking for a `Something` to be injected but registering your `Something` as an `ISomething`.

You have:
```fsharp
[<Inject>]
member val Something = Unchecked.defaultof<ISomething> with get,set
```

Try:
```fsharp
[<Inject>]
member val ISomething = Unchecked.defaultof<ISomething> with get,set
```

**Comment by ittennull** [comment]
```[<Inject>]
member val Something = Unchecked.defaultof<ISomething> with get,set
```
"Something" here is just a property name, it can be whatever, the type if inferred from ` Unchecked.defaultof<ISomething>`

For example:
`[<Inject>] member val WhateverName = Unchecked.defaultof<ISomething> with get,set`
" Cannot provide a value for property 'WhateverName' on type 'BoleroHostedApplication1.Client.Main+MyApp'. There is no registered service of type 'BoleroHostedApplication1.Client.Main+ISomething'"

**Comment by NickDarvey** [comment]
Oh dear, of course! Excuse me, jumping between languages.

I'll try one last thing before I drop out in shame. Try swapping [L#14](https://gitlab.com/ittennull/bolero_di_issue/-/blob/master/BoleroHostedApplication1/src/BoleroHostedApplication1.Client/Startup.fs#L14) and [L#13](https://gitlab.com/ittennull/bolero_di_issue/-/blob/master/BoleroHostedApplication1/src/BoleroHostedApplication1.Client/Startup.fs#L13). That's the only other difference that I can see compared to my app.

**Comment by ittennull** [comment]
Been there, done that :)
Swapping doesn't help

I think I'm missing something really simple and stupid, can't believe that such a basic functionality can be broken, it's probably not even implemented in Bolero and comes from Blazor and asp.net core and it works there

**Comment by Tarmil** [comment]
The problem is indeed with prerendering. During prerendering, the client application's `main` function isn't called. Instead, the dependency injection is done using aspnetcore's container. So any dependencies you need must also be injected in the server-side `ConfigureServices`.

If you don't want prerendering, then you can do `.AddBoleroHost(prerendering = false)` in `ConfigureServices`. If you want it, then to avoid code duplication, you can write a function that injects everything you need and call it from both the client and the server: https://gitlab.com/Tarmil/bolero_di_issue/-/commit/22f0200b807a09ac56a81af80717518f8d8b44d0

**Comment by ittennull** [comment]
Oh, I didn't know that thing about prerendering, I always thought it's an optimization and didn't care about it. Yes, it works now, thanks a lot!
