### ISSUE TITLE
Difference using Bolero vs F# library

### ISSUE THREAD

**Issue by IvanRainbolt** [fsbolero/Bolero#194]
My understanding is that Bolero downloads the Fsharp.core in Webassembly. If I used a standard C# Blazor Webassembly and added an F# library, then called my F# code from Blazor, is it still downloading the Fsharp.core? 

I not implementing the Elmish modules.

In essence, I am asking if there is advantage to building my component based on Bolero.Component vs just using ComponentBase?

**Comment by Tarmil** [comment]
What Bolero brings is the integration of Elmish, the syntax for HTML tags, and so on. But it uses FSharp.Core exactly the same way as any other F# library would. So if you have F# code that doesn't directly do UI, and is called by a C# Blazor application, then you don't need Bolero: you can just reference your F# library from your C# Blazor project, and it will download FSharp.Core as needed.

One thing you can still benefit from, though, is Bolero.Build. It removes some F#-specific metadata from F# assemblies, to make the download size smaller for webassembly applications. It doesn't depend on any other parts of Bolero, you can just add a NuGet dependency on it in your Blazor project.
