### ISSUE TITLE
Why does API Reference give 404?

### ISSUE THREAD

**Issue by IvanRainbolt** [fsbolero/Bolero#198]
When clicking on the website link "API Reference" which is https://fsbolero.io/docs/reference it displays a 404.
Is that just not producing or is that something that still needs to implemented to generate that?

**Comment by granicz** [comment]
Static documentation on the site is sourced from https://github.com/fsbolero/website/tree/master/src/Website/docs, except for the reference page, which is supposed to be generated with FSharp.Formatting, but I am not sure if that's all hooked up at the moment. It's likely a deployment issue, cc/ @Tarmil on this.

**Comment by Tarmil** [comment]
Yeah, the new Bolero.Html.dll didn't have a corresponding xml doc file and I missed the build error on the website. It's fixed now, thanks for the report!
