### ISSUE TITLE
Ref<'T>.Value should be an option type

### ISSUE THREAD

**Issue by MichaelMay81** [fsbolero/Bolero#205]
**Problem**:
Forgetting to set your Reference, but using it throws an Exception.

**Example**:
``` fsharp
comp<MatButton> [ attr.ref button; on.click (fun _ -> menu.Value.OpenAsync(button.Value.Ref)) ][  ]
comp<MatMenu> [ attr.ref menu ][]

```

Forgetting to set `attr.ref menu` gives a NullReferenceException.
Forgetting to set `attr.ref button` gives "Uncaught (in promise)" (probably because of a NullReferenceException)

**Sollution**:
Currently to avoid this you would have to check for null. The functional approach would be to use an option type.
I made this workaround to accomplish this:
``` fsharp
type RefOpt<'T>() =
    inherit Ref<'T option>()

    member val Value = None with get, set
    
    override this.Render(builder, sequence) =
        builder.AddComponentReferenceCapture(sequence, fun v ->
            this.Value <-
                match v with
                | :? 'T as result -> Some (result)
                | _ -> None)
        sequence + 1
```

**Comment by Tarmil** [comment]
I see where you're coming from. This is a possible solution to the problem, but it has the inconvenient that you now have to deal with an option when using it. Your callback would become much more verbose to check for None on two refs.

I would prefer a solution that helps you not forget to set the ref, if possible. For example, creating a ref could return a pair of values, a setter and a getter. This way, if you forget to set it, the setter will be grayed out in your editor, making it easy to spot the problem (and even tell you during compilation if you activate the unused variables warning).

```fsharp
type MyComponent() =
    inherit ElmishComponent<Model, Message>()

    let setMenu, menu = Ref.create<MatMenu>() // : Attr * Ref<MatMenu>

    // We forgot to use setButton below, so it's grayed out here:
    let setButton, button = Ref.create<MatButton>()

    override this.View model dispatch =
        concat [
            comp<MatButton> [ on.click (fun _ -> menu.Value.OpenAsync(button.Value.Ref)) ][  ]
            comp<MatMenu> [ setMenu ][]
        ]
```

**Comment by MichaelMay81** [comment]
Yeah, I know what you mean. But I feel that Option is still the more robust way.
The shortest I could come up with having two Options is:
``` fsharp
comp<MatButton>
   [ attr.ref button; on.click (fun _ -> button.Value |> (menu.Value |> Option.map2 (fun m b -> m.OpenAsync b.Ref)) |> ignore) ]
   [  ]
comp<MatMenu> [ attr.ref menu ][]
```
If we expand Ref we could get:
``` fsharp
comp<MatButton>
   [ attr.ref button; on.click (fun _ -> button |> (menu |> Ref.map2 (fun m b -> m.OpenAsync b.Ref)) |> ignore) ]
   [  ]
comp<MatMenu> [ attr.ref menu ][]
```
Still not as convenient as I would wish for....

**Comment by MichaelMay81** [comment]
if OpenAsync wheren't a class method but a function, this would look kinda nice:
```
comp<MatButton>
   [ attr.ref button; on.click (fun _ -> Ref.map2 openAsync menu button |> ignore) ]
   [  ]
comp<MatMenu> [ attr.ref menu ][]
```

**Comment by Tarmil** [comment]
Actually, I'm thinking the options don't even solve the issue of forgetting to set the ref. If you use an option the way you're suggesting, then instead of a NullReferenceException, you just see nothing happening. Which is even less helpful to figure out what's wrong. For the options to actually be helpful, you would need to do this:

```fsharp
comp<MatButton> [
    attr.ref button
    on.click (fun _ ->
        match button.Value, menu.Value with
        | None, _ -> failwith "Forgot to set button ref"
        | _, None -> failwith "Forgot to set menu ref"
        | Some button, Some menu -> menu.OpenAsync(button.Ref))
] ...
```

In the end, I think we can implement this logic but hidden inside Ref:

```fsharp
type Ref<'T>() =
    inherit Ref()

    let mutable value : 'T option = None

    member this.Value : 'T =
        match value with
        | None -> failwith "Forgot to set %s ref" typef<'T>.FullName
        | Some value -> value

    override this.Render(builder, sequence) =
        builder.AddComponentReferenceCapture(sequence, fun v -> value <- Some (unbox<'T> v))
        sequence + 1
```

As a bonus, it's a non-breaking change.

**Comment by MichaelMay81** [comment]
Nonono, forgetting to set the reference is the trigger, but the thrown Exception is the actual problem and you just switched out one exception for another. I rather have a reference not working in my running app instead of the whole app crashing because of an uncaught exception! I used map because I tried to get to a simple non verbose version. If you use a Match the compiler would warn you if you don't handle None.

You could do this for error handling:
``` fsharp
let map2OrElseWith ifNoneThunk mapping (option1:RefOpt<'T1>) (option2:RefOpt<'T2>) =
        match option1.Value, option2.Value with
        | Some o1, Some o2 -> mapping(o1, o2)
        | _, _ -> ifNoneThunk()
...
let map2OrElseLog = RefOpt.map2OrElseWith (fun _ -> dispatch (LogError "You forget to set a Reference!")) 
...
 comp<MatButton>
   [ attr.ref button; on.click (fun _ -> map2OrElseLog openAsync menu button |> ignore) ] []
```
Than in update you could throw an exception on that message in Debug and only write a message on the console for Release builds.

**Comment by MichaelMay81** [comment]
Option could still be combined with the Get/Set idea.

Or all of those ideas could be put inside Ref and let the user choose what to use. But I urge against that. I really think Exceptions and therefore Null which can lead to Exceptions should be avoided in functional programming at all costs!

**Comment by Tarmil** [comment]
So I've been thinking about this a bit. I still don't quite like the boilerplate you're adding in your specific example, especially considering that it's simplified because it ignores the return value of the `OpenAsync` method. Across an application you might end up needing a whole set of these combinators, depending on the number of refs, the sync/async result, etc.

But then I realized that it would be made nicer and more consistent by adhering more closely to MVU, and moving the call to a command:

```fsharp
type Message =
    | OpenMenu of menu: MatMenu option * button: MatButton option
    | OpenedMenu
    | Error of exn

let update message model =
    match message with
    | OpenMenu (Some menu, Some button) ->
        model, Cmd.OfTask.either menu.OpenAsync button (fun () -> OpenedMenu) Error
    | OpenMenu _ ->
        model, Cmd.ofMsg (Error (exn "You forgot to set a reference!"))
    | OpenedMenu ->
        model, Cmd.none // If OpenAsync had a Task<_> result, you could process it here
    // ...

type MyComponent() =
    inherit ElmishComponent<Model, Message>()

    let menu = Ref<MatMenu>()
    let button = Ref<MatButton>()

    override this.View model dispatch =
        concat [
            comp<MatButton> [ attr.ref button; on.click (fun _ -> dispatch (OpenMenu (menu.Value, button.Value))) ] []
            comp<MatMenu> [ attr.ref menu ][]
        ]
```

**Comment by MichaelMay81** [comment]
Uh, I like it!
I would love to implement that for you...

**Comment by MichaelMay81** [comment]
Just a remark: I would not use unbox, but match with a type test pattern as I did in my first comment. This avoids getting ```Some null``` and returns None if it gets null.
I know it is not much to implement, but I would love to contribute. Tell me if I should do it?

**Comment by Tarmil** [comment]
Or use `tryUnbox` 😉
