### ISSUE TITLE
Bolero failed to strip F# metadata from Bolero.dll

### ISSUE THREAD

**Issue by ericdes** [fsbolero/Bolero#214]
Hello, I created a Bolero client project (--server false), and when trying to publish it, I'm getting this error:

> Severity	Code	Description	Project	File	Line	Suppression State
> Error		Bolero failed to strip F# metadata from obj\Release\net5.0\linked\Bolero.dll: Could not find file 'C:\Dev\MyApp\MyApp.App\obj\Release\net5.0\linked\System.Runtime.dll'.	Intv.App		0	

Have you experienced a similar problem?

Thank you,

**Comment by ericdes** [comment]
I narrowed down the problem to introducing some variations in the publishing options. 

Below is an easy step to reproduce the error:

(1) Install the default template as follows:
`dotnet new bolero-app -o MyBoleroApp --minimal=true --server=false`

(2) Open in Visual Studio 2019 and publish to folder:
`C:\Dev\Published_1`

(3) Getting this sucessuful result 
`========== Publish: 1 succeeded, 0 failed, 0 skipped ==========`

(4) Now change the folder target to
`C:\Dev\Published_2`

(4) Getting this failed result:
`Bolero failed to strip F# metadata from obj\Release\net5.0\linked\Bolero.dll: Could not find file 'C:\Dev\MyBoleroApp\src\MyBoleroApp.Client\obj\Release\net5.0\linked\System.Runtime.dll'.`

**Comment by Tarmil** [comment]
It actually looks like there's a bug with .NET's trimming itself. When I add `<BoleroStripAssemblies>false</BoleroStripAssemblies>` to a project so that Bolero's F# metadata stripper doesn't run, and then do the same thing as you (publish, change directory, publish again), the two output directories don't have the same contents. The first one is correct, but the second contains untrimmed assemblies.

**Comment by Tarmil** [comment]
Ah, no, I see what's going on. It's more of an issue with VS's publish interface. The default publish mode is self-contained and trimmed, which makes sense for a wasm project. But when you open the Edit window to change the output directory, instead of keeping these settings, it sets the deployment mode to Framework-Dependent (and doesn't trim because that's only possible in Self-Contained mode). That's why the output is incorrect. But if you select Deployment Mode: Self-Contained, and then under File Publish options you check "Trim unused assemblies", then the result is correct and Bolero's metadata stripping can run.

Now, this does reveal a real issue in Bolero, which is that metadata stripping only works in trimmed mode, and fails when doing an untrimmed publish. I'll see what I can do about that.

**Comment by ericdes** [comment]
I confirm that publish now succeeds. Thank you!

![image](https://user-images.githubusercontent.com/81717/118249981-44fe0100-b4a6-11eb-88bc-a17ae03696d6.png)

**Comment by dallinbeutler** [comment]
Hey, just wondering if there's an update on this? I'm trying to publish right now and I can't get that pesky `Error Bolero failed to strip F# metadata from` error to go away.
Best guess at settings:
![image](https://user-images.githubusercontent.com/9158155/157758984-3307e989-04f8-4d91-8506-33deab6b711d.png)
server 's .fsproj:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>
<ItemGroup>...</ItemGroup>
  <ItemGroup>
    <PackageReference Include="Blazored.LocalStorage" Version="4.1.5" />
    <PackageReference Include="Bolero.Server" Version="0.*" />
    <PackageReference Include="Bolero.HotReload.Server" Version="0.*" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="5.0.*"/>
    <PackageReference Include="SQLProvider" Version="1.2.10" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.3" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="FSharp.Core" Version="6.0.1" />
  </ItemGroup>
</Project>
```

**Comment by Tarmil** [comment]
The metadata stripping is done on the client project, not server. What happens if you disable ReadyToRun compilation?

**Comment by dallinbeutler** [comment]
Oh, my bad, here's the client .fsproj:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    ...
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Blazored.LocalStorage" Version="4.1.5" />
    <PackageReference Include="Bolero" Version="0.*" />
    <PackageReference Include="Bolero.Build" Version="0.*" />
    <PackageReference Include="Bolero.HotReload" Version="0.*" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer"Version="5.0.*" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="6.0.0" />
    <PackageReference Include="System.Net.Http.Json" Version="5.0.*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference ... />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="FSharp.Core" Version="6.0.3" />
  </ItemGroup>
</Project>
```
I disabled ReadyToRun, same exact error

**Comment by Tarmil** [comment]
I just realized that you're probably not based on the latest version of the project template, since you're targeting net5.0. I'm curious what exact package versions are referenced, can you paste the output of `dotnet list package`?

**Comment by dallinbeutler** [comment]
I just wanna say thanks for prompt communication! 
Here it is:
```
 dotnet list package
Project 'Chat.Server' has the following package references
   [net5.0]:
   Top-level Package                                         Requested   Resolved
   > Blazored.LocalStorage                                   4.1.5       4.1.5
   > Bolero.HotReload.Server                                 0.*         0.18.16
   > Bolero.Server                                           0.*         0.18.16
   > FSharp.Core                                             6.0.1       6.0.1
   > Microsoft.AspNetCore.Components.WebAssembly.Server      5.0.*       5.0.15
   > SQLProvider                                             1.2.10      1.2.10
   > System.Data.SqlClient                                   4.8.3       4.8.3

Project 'Chat.Client' has the following package references
   [net5.0]:
   Top-level Package                                            Requested   Resolved
   > Blazored.LocalStorage                                      4.1.5       4.1.5
   > Bolero                                                     0.*         0.18.16
   > Bolero.Build                                               0.*         0.18.16
   > Bolero.HotReload                                           0.*         0.18.16
   > FSharp.Core                                                6.0.1       6.0.1
   > Microsoft.AspNetCore.Components.WebAssembly.DevServer      5.0.*       5.0.15
   > Microsoft.Extensions.Logging.Console                       6.0.0       6.0.0
   > System.Net.Http.Json                                       5.0.*       5.0.0

Project 'FSharpSQLAccess' has the following package references
   [net5.0]:
   Top-level Package      Requested   Resolved
   > FSharp.Core          6.0.1       6.0.1
   > SQLProvider          1.2.10      1.2.10

Project 'chat-shared' has the following package references
   [netstandard2.1]:
   Top-level Package                          Requested   Resolved
   > Elmish                                   3.1.0       3.1.0
   > FSharp.Core                              6.0.1       6.0.1
   > FSharp.SystemTextJson                    0.17.4      0.17.4
   > Microsoft.AspNetCore.SignalR.Client      5.0.0       5.0.0
   > Myriad.Core                              0.7.4       0.7.4
   > Myriad.Plugins                           0.7.4       0.7.4
   > Myriad.Sdk                               0.7.4       0.7.4
   ```

**Comment by dallinbeutler** [comment]
so I installed .NET6, the latest templates, and tested with a sample project still getting the same error. 
dotnet list package:
```
Project 'BasicBolero.Server' has the following package references
   [net6.0]:
   Top-level Package                                         Requested   Resolved
   > Bolero.HotReload.Server                                 0.*         0.18.16
   > Bolero.Server                                           0.*         0.18.16
   > FSharp.Core                                             6.0.2       6.0.2
   > Microsoft.AspNetCore.Components.WebAssembly.Server      6.0.*       6.0.3

Project 'BasicBolero.Client' has the following package references
   [net6.0]:
   Top-level Package                                            Requested   Resolved
   > Bolero                                                     0.*         0.18.16
   > Bolero.Build                                               0.*         0.18.16
   > Bolero.HotReload                                           0.*         0.18.16
   > FSharp.Core                                                6.0.2       6.0.2
   > Microsoft.AspNetCore.Components.WebAssembly.DevServer      6.0.*       6.0.3
   ```
