### ISSUE TITLE
Show element if true

### ISSUE THREAD

**Issue by pipsy100** [fsbolero/Bolero#222]
I have this code in a HTML Template:

      <template id="Hello">
        <h1 class="title">Hello</h1>
        <p>
          ShowOrNotShow
        </p>
      </template>

This must only be visible when Show(bool) in app.fs is true.
If false do not show anything.

What is the best way to achieve this?

**Comment by Tarmil** [comment]
You would implement something like this directly in F#:

```fsharp
cond model.Show <| function
| true -> MyTemplate.Hello().Elt()
| false -> empty
```

**Comment by Pipsy100** [comment]
Hello, another question(newbie).
I want to add Bulma to the Client project.
What is the best way?

Thx Pipsy

7 Jun 2021 10:22:48 Loïc Denuzière ***@***.***>:

**Comment by akhansari** [comment]
You can simply add
`<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.9.2/css/bulma.min.css" integrity="sha512-byErQdWdTqREz6DLAA9pCnLbdoGGhXfU6gm1c8bkf7F51JVmUBlayGe2A31VpXWQP+eiJ3ilTAZHCR3vmMyybA==" crossorigin="anonymous" />`
into `index.html`
