### ISSUE TITLE
How to handle property like System.Func<_, Microsoft.AspNetCore.Components.RenderFragment>?

### ISSUE THREAD

**Issue by albertwoo** [fsbolero/Bolero#235]
I am trying to use AntDesign for bolero, component calender has properties like:
```fsharp
"MonthCellRender" => (System.Func<System.DateTime, Microsoft.AspNetCore.Components.RenderFragment>fn)
```
https://github.com/ant-design-blazor/ant-design-blazor/blob/c46a457f53984ecc92e4782710897c77bff57ab0/components/date-picker/internal/DatePickerPanelBase.cs#L66

How do I define my fn? Because it returns a RenderFragment, but it is not like RenderFragment<'T>.
Could anyone help me on this?

**Comment by Tarmil** [comment]
Oh, this is the first time I've seen a parameter like this... I think something like this should do the trick:

```fsharp
module attr =

    let funcFragment (name: string) (f: 'T -> Node) : Attr =
        FragmentAttr (name, fun render ->
            box <| Func<'T, RenderFragment>(fun x ->
                RenderFragment(fun rt -> render rt (f x))))

    let funcFragment2 (name: string) (f: 'T -> 'U -> Node) : Attr =
        FragmentAttr (name, fun render ->
            box <| Func<'T, 'U, RenderFragment>(fun x y ->
                RenderFragment(fun rt -> render rt (f x y))))
```

And then call it with:

```
comp<DatePickerPanelBase<DateTime>> [
    attr.funcFragment "MonthCellRender" <| fun date ->
        div [] [text $"{date.Month}"]
] []

**Comment by albertwoo** [comment]
Thanks, it works great. I added to my little generator and now I can just write like:
```fsharp
calendar.create [
    calendar.monthCellRender (fun d -> html.text $"My {d.Month}")
]
```
https://github.com/slaveOftime/Fun.Blazor/blob/0217521b623bed1472efab531b35cdfdbba4aed1/Fun.Blazor.Docs.Wasm/Demos/DemoAntDesign/ModalDemo.fs#L42-L44
