### ISSUE TITLE
Remoting Authentication

### ISSUE THREAD

**Issue by weebs** [fsbolero/Bolero#24]
Is it possible to incorporate authentication into remote requests? Something along the lines of attaching a header value to include a JWT token to be included in the HTTP request?

**Comment by Tarmil** [comment]
I have work in progress to allow using standard ASP.NET Core authentication in remote functions, see #30. With it you can use whichever authentication scheme you prefer using ASP.NET Core's API: cookies, JWT, etc.

**Comment by Tarmil** [comment]
This was added in v0.4.
