### ISSUE TITLE
Blazor AoT WASM is huge and slow

### ISSUE THREAD

**Issue by Martin521** [fsbolero/Bolero#246]
Has anybody tried the new Blazor AOT feature with Bolero?
Here is my experience.
a) Size
Without AOT, the total deployment size of my client-only application (statically hosted) is about 9 MB, of which 0.5 MB is my own code (2 .dll files). With AOT, I end up with a whopping 42 MB dotnet.wasm file. Yes, 42.
b) Speed
In my application, I have some CPU intensive actions. I have measured them inside a desktop application
and inside Bolero with and without AOT.
Without AOT the speed factor between wasm and desktop is about 10 (I have seen similar numbers reported by others).
With AOT I expected an acceleration but found a factor of 18. Really slow.

I would like to know how this plays out in other applications. Anybody who tried it?
Also, I wonder if people think that this whole WASM path has a future.

I really like Bolero (because it is real F# and also Elmish is nice), but wonder if I should go back to Websharper, or try SAFE.

**Comment by granicz** [comment]
Running on JS is becoming less and less future-proof by the day. I have yet to try what you are describing above (might just be a glitch or a misconfiguration), but I am sure AOT will be a bumpy ride initially, only to pay off big time later.

**Comment by Martin521** [comment]
That's good to hear. Thanks.
