### ISSUE TITLE
Q: how to set or clear the value of an input element

### ISSUE THREAD

**Issue by Martin521** [fsbolero/Bolero#247]
I have a modal form that I hide and unhide by means of the Bulma "is-active" class. The form contains an Input element. I would like the input to be empty when I unhide the form, but I don't find a way to do it, neither through bind.input.string nor through setting the value attribute. The Input element always shows the previous value (content). Is there a way to set or reset the value?
Or, alternatively, is there a way to ensure that the Input element is recreated by the view (by Blazor) rather than reused?

**Comment by granicz** [comment]
You can access the input control's value if you have a `ws-var` on it. Then you can reassign this to your own reactive variable that is in scope for the hide/unhide handler, and set it there to clear the value on unhide.

**Comment by Martin521** [comment]
Thing is I don't use templates, therefore not `ws-var` (or rather a `bind` attribute in Bolero). I am creating everything in [code](https://fsbolero.io/docs/HTML), and bind through the Bolero.Html.bind.input.string function.

**Comment by Martin521** [comment]
I actually wonder if this is a bug in bind.input.string, or if the behavior is intended. I would expect the input value to be reset when the control and the binding are recreated in the view function.
Unfortunately, I don't understand the bind.binder code well enough to check this.

**Comment by Martin521** [comment]
I have created an example [here](https://github.com/Martin521/BoleroInputBinding) by extending the Bolero demo by a page with an input control. I would expect that clicking the Reset button erases the text (through the `ResetInput` message). But it does not.

I assume this is an unintended  behavior of `bind.input.string` function. I would be happy to help digging further to resolve this, but I don't understand the bind.binder code well enough to do this.

**Comment by Tarmil** [comment]
I think I see the misunderstanding about `bind`. The way it should be used is that its dispatch message should set the same model value that is passed to its first argument. With your code, `model.inputString` is simply never changed to reflect user input, so when you set it to `""` in `ResetInput`, nothing happens.

Let's take a step back. The Reset button's purpose is to reset the `inputString`. The fact that this will, in turn, set the label to `v.Upper()` is none of the view function's business; it should happen in the update function. Here is how I would do it: https://github.com/Tarmil/BoleroInputBinding/commit/13ecf2c7ffb6a0d0bb577ada508b0a1ff4bb1141

**Comment by Martin521** [comment]
Thanks for the fast response.

This helped me find the issue (a really stupid one) that I had in my real project. When the simple example showed the same effect (for a different reason), I concluded too quickly. Sorry for bothering you.

And thanks again for creating Bolero.
