### ISSUE TITLE
Trimming removes method required by Bolero.Html.comp

### ISSUE THREAD

**Issue by ed-ilyin** [fsbolero/Bolero#250]
Hi,

When I do `dotnet run —project src/Client -c Release` or `Debug` (doesn’t matter) Bolero SPA works just fine.
When I do `dotnet publish src/Client -c Release` or `Debug` (doesn’t matter) app throws:
```
blazor.webassembly.js:1

       crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Arg_NoDefCTor, Microsoft.AspNetCore.Components.Authorization.CascadingAuthenticationState
System.MissingMethodException: Arg_NoDefCTor, Microsoft.AspNetCore.Components.Authorization.CascadingAuthenticationState
   at System.RuntimeType.CreateInstanceMono(Boolean , Boolean )
```
if I remove `comp<CascadingAuthenticationState>` from my app, same error but for different Component (`comp<InputFile>`) is thrown.
If I remove `comp<InputFile>` all works even in published version.
Why publish stops app from functioning?

**Comment by ed-ilyin** [comment]
I’ve created narrowed down minimal sample: https://github.com/ed-ilyin/BoleroTrimmingIssue to reproduce the issue.
Do you know any workaround meanwhile?

**Comment by Tarmil** [comment]
I believe we can fix this issue using attributes to tell the trimmer that the type passed as attribute is used entirely.

For a workaround in the meantime, I think you can add a [descriptor file](https://docs.microsoft.com/en-us/dotnet/core/deploying/trimming/trimming-options#root-descriptors) that lists the components you're using so that they're not trimmed.

**Comment by ed-ilyin** [comment]
Thank you very much for help @Tarmil,
I found which exactly assembly raises trimming issue and changes the minimal repo to skip trimming for it.
Now original error not there anymore, but a new related one appeared in same conditions:
```
Uncaught (in promise) Error: Invalid JS call result type '3'.
    at _ (blazor.webassembly.js:1:4820)
    at blazor.webassembly.js:1:4045
```
What you think could help in such case?
https://github.com/ed-ilyin/BoleroTrimmingIssue

**Comment by ed-ilyin** [comment]
somehow adding the line below to the .fsproj solves the last issue:
```
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="6.0.*" />
```
Can't understand why.
