### ISSUE TITLE
toggling CSS classes with Bolero

### ISSUE THREAD

**Issue by BryanWilhite** [fsbolero/Bolero#254]
it appears that it is possible to [toggle CSS classes in Blazor](https://www.syncfusion.com/faq/blazor/data-binding/how-do-i-conditionally-change-the-css-class-names-for-a-blazor-element):

![image](https://user-images.githubusercontent.com/5226627/163909211-afb06ae5-822b-4d2c-aa69-3c77012bbbda.png)

Does Bolero have equivalent functionality? Failing this, would Blazor get into an undetermined state from editing `DOMTokenList` with JavaScript `classList` methods [ 📖 [MDN]](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList)?

**Comment by Martin521** [comment]
Of course you can do that in F# in Bolero. Either using [attribute holes](https://fsbolero.io/docs/Templating#holes) or [by defining the html in F#](https://fsbolero.io/docs/HTML#attributes).

**Comment by Tarmil** [comment]
Yes, you can use an interpolated string to do something very similar to the blazor example:

```fsharp
attr.``class`` $"""menu {if model.IsOpen then "open" else ""}"""
```

**Comment by BryanWilhite** [comment]
thanks @Tarmil and I also see (the obvious) that this is an Elmish matter, a natural part of the message-update-view cycle as suggested in the docs (“Conditional attributes”):

![image](https://user-images.githubusercontent.com/5226627/164026926-8ace1175-3bcf-45d1-b9d2-58564d761552.png)
[ https://fsbolero.io/docs/HTML ]
