### ISSUE TITLE
`attr.ref` cannot combine with other attributes [version 0.20.17]

### ISSUE THREAD

**Issue by BryanWilhite** [fsbolero/Bolero#260]
Even though I can [see some effort](https://github.com/fsbolero/Bolero/blob/fbf5ffef49c732347dd79b69ca0e8a7ce38a6554/src/Bolero.Html/Builders.fs#L151) to `Combine` type `RefContent` with other attributes I am seeing this error in JetBrains Rider:

```console
No overloads match for method 'Combine'. 

Known types of arguments: Builders.RefContent * Attr 

Available overloads:

- member Builders.ElementBuilder.Combine: x1: Attr * x2: Attr -> Attr // Argument 'x1' doesn't match
- member Builders.ElementBuilder.Combine: x1: Attr * x2: Builders.ChildAndRefContent -> Attr // Argument 'x1' doesn't match
- member Builders.ElementBuilder.Combine: x1: Attr * x2: Builders.RefContent -> Attr // Argument 'x1' doesn't match
- member Builders.ElementBuilder.Combine: x1: Attr * x2: Node -> Attr // Argument 'x1' doesn't match
- member Builders.ElementBuilder.Combine: x1: Builders.RefContent * x2: Node -> Builders.ChildAndRefContent // Argument 'x2' doesn't match
- member Builders.ElementBuilder.Combine: x1: Node * x2: Node -> Node // Argument 'x1' doesn't match
```

![image](https://user-images.githubusercontent.com/5226627/173256225-fed473f8-ca9f-4479-bde6-3c14be9604e5.png)

When `attr.ref` is used by itself there is no error.

**Comment by Tarmil** [comment]
Maybe I should make it more prominent in the docs: with the new CE syntax, refs must be listed *after* normal attributes (and before children).

**Comment by BryanWilhite** [comment]
Thanks @Tarmil !

![image](https://user-images.githubusercontent.com/5226627/173376260-8b0b0f9c-8dae-4d74-bd1e-96005e8d812a.png)
