### ISSUE TITLE
`rootComp` can no longer prerender? [version 0.20.*]

### ISSUE THREAD

**Issue by BryanWilhite** [fsbolero/Bolero#261]
In the `0.18.*` era of Bolero, by default, contents of `rootComp` would prerender:

![image](https://user-images.githubusercontent.com/5226627/173487284-ac1ae085-062a-418d-bccc-9e3f9135c04f.png)

This is not the case for `0.20.*`:

![image](https://user-images.githubusercontent.com/5226627/173487535-23fb73b7-dfd3-4d88-91d0-7ba1cc153b88.png)

In `Songhay.Dashboard.Server/Startup.fs`:

```fsharp
.AddBoleroHost(server = false, prerendered = true, devToggle = true)
```

Is this just a fact of life with the new CE technology? Are there other ways to control `RenderMode` apart from [using Razor](https://fsbolero.io/docs/Hosting#razor) and calling `Html.RenderComponentAsync` explicitly?

![image](https://user-images.githubusercontent.com/5226627/173488039-929aa640-3923-4d10-a1dd-da968c76556f.png)

**Comment by BryanWilhite** [comment]
I can change my current layout to respond to what I am experiencing:

![image](https://user-images.githubusercontent.com/5226627/173734607-45321a63-a3b9-44d9-9ccb-ae84522b1a93.png)

The dashed lines represent visuals rendered by `rootComp`. The layout on the left is what I have now. The layout on the right reduces the responsibility of `rootComp` and places static visuals _around_ `rootComp`.

Even with this reduced rendering functionality, the prerender feature is still there, making it superior to all popular JavaScript-based SPAs out of the box!

**Comment by Tarmil** [comment]
This definitely looks like a bug, the change is not intentional. I'll look into it.
