### ISSUE TITLE
cannot throw exception inside of CE builder blocks

### ISSUE THREAD

**Issue by jkone27** [fsbolero/Bolero#269]
![image](https://user-images.githubusercontent.com/10419217/188101637-b9a9cfb4-c1c8-4000-ba1f-92d83b85c48a.png)

while with the previous format it was working fine

div [] [
 ...
]

now 

div {
...
}

**Comment by Tarmil** [comment]
Indeed, this should be fixable. Meanwhile, this workaround should work:

```fsharp
| _ -> failwith "error"; empty()
```

**Comment by Tarmil** [comment]
This was added in Bolero 0.22.
