### ISSUE TITLE
WASM compilation without UI?

### ISSUE THREAD

**Issue by mindlid** [fsbolero/Bolero#270]
Searching for a way to do calculations in WASM, without UI, however all bolero templates produce a webpage with HTML, is there a way to generate a single wasm file that can be imported in any js application? like tryfsharp. https://tryfsharp.fsbolero.io/?snippet=HelloWorld

I just need to compile F# to WASM and call from JS, Bolero feels much more.

**Comment by Tarmil** [comment]
Well, you can just remove all the UI code and just write functions that you call from js using [JavaScript interop](https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-dotnet-from-javascript?view=aspnetcore-6.0).

It could be worth adding a project template that sets this up nicely though.

**Comment by mindlid** [comment]
would be nice, to understand how the build is imported, i was trying to figure which of the bin files

**Comment by Tarmil** [comment]
You need to put the whole `_framework` folder in your application, and to load the file `_framework/blazor.webassembly.js`.

**Comment by Tarmil** [comment]
They're adding [a dedicated Blazor template for JS interop](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-rc-1/#net-javascript-interop-on-webassembly) in .NET 7, so it would make sense to make a corresponding F# template.

**Comment by mindlid** [comment]
would be possible to hot reload for WASM as well?
