### ISSUE TITLE
Is using `attrs.Combine` generally safe?

### ISSUE THREAD

**Issue by BryanWilhite** [fsbolero/Bolero#271]
Can `attrs.Combine` be regarded as the `Attr` equivalent for `concat` for `Node`?

I have a type I am experimenting with:

```fsharp
type HtmlAttributesOrEmpty =
    | NoAttributes
    | HasAttributes of Attr list

    member this.Value =
        match this with
        | NoAttributes -> attr.empty()
        | HasAttributes attributes ->
            match attributes with
            | [ a ] -> a
            | _ -> attributes |> List.reduce(fun a b -> attrs.Combine(a, b))
```

I am using it like this:

![image](https://user-images.githubusercontent.com/5226627/189391157-5fb77dcd-28f7-4bf4-b9d8-88856c8bc629.png)

Are there any dangers (perhaps related to Computation Expressions) I am flirting with here?

**Comment by Tarmil** [comment]
This should be safe as long as you build a static list of attributes, and only their values depend on the model.

That being said, it's equivalent to using `attrs` as a computation expression, except slightly worse performance-wise because it builds a list.

**Comment by BryanWilhite** [comment]
after more thought, I also have a recommendation for myself: avoid using/returning `Node list` or `Attr list` because these types can almost always be replaced by `Node` or `Attr` because @Tarmil has provided us with the `concat` and `attrs` functions, respectively. These functions take us back to using computation expressions which is intended by design instead of collections like `List`
