### ISSUE TITLE
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]

### ISSUE THREAD

**Issue by Bananas-Are-Yellow** [fsbolero/Bolero#287]
I'm getting this exception in the browser console window:

```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Method not found: int Bolero.Node.Invoke(object,Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder,Microsoft.FSharp.Core.FSharpFunc`2<System.Type, System.Tuple`2<int, Microsoft.FSharp.Core.FSharpFunc`2<object, int>>>,int)
System.MissingMethodException: Method not found: int Bolero.Node.Invoke(object,Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder,Microsoft.FSharp.Core.FSharpFunc`2<System.Type, System.Tuple`2<int, Microsoft.FSharp.Core.FSharpFunc`2<object, int>>>,int)
   at Bolero.Component.BuildRenderTree(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
```

I was able to reproduce it by taking a copy of the **HelloWorld** example project I had lying around, which was working fine, and then doing a `dotnet paket update`. But then, if I revert my changes, the problem does not go away. Here is the `packet.lock` file at the time it was working, before I did the `dotnet paket update`:

```
STORAGE: NONE
RESTRICTION: == net7.0
NUGET
  remote: https://api.nuget.org/v3/index.json
    FSharp.Core (7.0)
    FSharpPlus (1.3.2)
      FSharp.Core (>= 6.0.6)
```
After the `dotnet paket update`, it changed to this:
```
STORAGE: NONE
RESTRICTION: == net7.0
NUGET
  remote: https://api.nuget.org/v3/index.json
    FSharp.Core (7.0.200)
    FSharpPlus (1.3.3)
      FSharp.Core (>= 6.0.6)
```
This is when the problem started, but like I said, if I revert my `paket.lock`, the problem is still there.

I've tried `dotnet paket clear-cache --clear-local` and `dotnet tool restore` and `dotnet paket restore` but nothing helps. Once the problem is there, I can't seem to get rid of it.

I've no idea whether this is a Bolero issue, or a Paket issue, or a Blazor WebAssembly issue, but I thought I'd post here to start with.

**Comment by Bananas-Are-Yellow** [comment]
OK, it has nothing to do with Paket. That HelloWorld project I had lying around must have been created with the Paket option (and I may even have changed the code from the stock sample), but I can recreate the problem very simply using the non-paket version:
```
dotnet new bolero-app -o HelloWorld
```
Just build and run the sample. As soon as you change page (e.g. from Home to Counter), the exception appears in the browser console.

Then, if you refresh the page, the exception now appears in the VS Code terminal window.

**Comment by Martin521** [comment]
I can confirm and reproduce this.
There is also a corresponding client exception:
```
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Method not found: int Bolero.Node.Invoke(object,Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder,Microsoft.FSharp.Core.FSharpFunc`2<System.Type, System.Tuple`2<int, Microsoft.FSharp.Core.FSharpFunc`2<object, int>>>,int)
System.MissingMethodException: Method not found: int Bolero.Node.Invoke(object,Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder,Microsoft.FSharp.Core.FSharpFunc`2<System.Type, System.Tuple`2<int, Microsoft.FSharp.Core.FSharpFunc`2<object, int>>>,int)
   at Bolero.Component.BuildRenderTree(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)```

**Comment by Bananas-Are-Yellow** [comment]
I think the problem is with Bolero 0.21 which was released 3 days ago. If I edit the Server and Client project files and choose the previous version, the problem goes away.

In each of the two project files, I changed this:
```
<PackageReference Include="Bolero" Version="0.*" />
```
into this:
```
<PackageReference Include="Bolero" Version="0.20.18" />
```
Then it worked.

**Comment by Tarmil** [comment]
Ah, I think the problem is that indeed the type Node has changed in v0.21, but the HotReload packages haven't been updated to match. I'll unlist v0.21 immediately, and restore it once I've updated HotReload (and done the release announcement 😄)

**Comment by Tarmil** [comment]
I have now published HotReload 0.21. Can you try and update Bolero and HotReload to 0.21? I expect it should fix this issue.

**Comment by Bananas-Are-Yellow** [comment]
Works now! Thanks.

**Comment by Tarmil** [comment]
Awesome!
