### ISSUE TITLE
Use endpoint routing for remoting

### ISSUE THREAD

**Issue by Tarmil** [fsbolero/Bolero#289]
Remoting currently uses a middleware, and it should be more performant using endpoint routing.

**Comment by granicz** [comment]
We have been discussing this for WebSharper for a while, makes perfect sense. Have you thought of a way to include server-push remoting (using websockets)?

**Comment by Tarmil** [comment]
@granicz A small wrapper for the SignalR client and server libraries would probably be the way to go for this (HotReload already uses them, for example), but I haven't looked into it recently.

**Comment by fwaris** [comment]
I have started to use bolero now. However, I am finding that server-based push is a key need for me. I am using bolero to build live dashboards and monitoring systems.

I have signalR working with the following wasm-side snippet to create the connection:
```F#
open Microsoft.AspNetCore.SignalR.Client
...
let subscription (loggerProvider: ILoggerProvider) (navMgr:NavigationManager) (dispatch: _ -> unit) =
    let hubConnection =
        HubConnectionBuilder()               
            .AddJsonProtocol(fun o -> SerializationOptions.configureSerialization o.PayloadSerializerOptions)//.Converters.Add (JsonFSharpConverter()))
            .WithUrl(navMgr.ToAbsoluteUri("/chartdata"))
            .WithAutomaticReconnect()           
            .ConfigureLogging(fun logging ->
                logging.AddProvider(loggerProvider) |> ignore
            )           
            .Build()

    hubConnection.On<UI_Update> ("ChartUpdate", dispatch) |> ignore
    (hubConnection.StartAsync()) |> Async.AwaitTask |> Async.Start
    hubConnection    
```
The connection is hosted in a Component to receive pushed data. (note it took a while for me to sort out all the different pieces to make it all work. Many thanks to others!)

I would appreciate a more elegant solution and integrated solution. 
(Also I think hot-reloading stops working when I use SignalR this way)

**Comment by Tarmil** [comment]
I tried using Elmish.Bridge, as it has [a .NET client](https://www.nuget.org/packages/Elmish.Bridge.DotnetClient). Unfortunately when I tried to use it, the browser froze. I'm guessing that its direct use of System.Net.WebSockets (as opposed to SignalR.Client) may be the cause.

So I guess a more Bolero-centric, SignalR-based solution will be necessary.
