### ISSUE TITLE
How to get an element reference when using templates

### ISSUE THREAD

**Issue by kgday** [fsbolero/Bolero#290]
I see that one can get a reference to html element that you can then use with JSInterop if you use the computation expressions to define your view.  But what if you use a html template with the template provider?

**Comment by Tarmil** [comment]
That is indeed not possible right now. But it would be fairly easy to add this capability.

**Comment by kgday** [comment]
Thanks Tamil,
I just needed to focus an element so did that by tagging the id and using jsinterop to find the item by id and focus. However I probably could return the reference from the javascript if I needed more.

For anyone else's benefit who need to do something similar:

In my index.js
window.utilFuncs =
{
    focusElementByID: function (id) {
        const myElement = document.getElementById(id)
        myElement.focus();
    }
}

I called that then with
    let checkBoxID jobID = $"SelectionCheck%d{jobID}"
    let focusJobIDSelection (jobID: int64) =
        task {
            let elementID = checkBoxID jobID

            return!
                (jSRuntime.InvokeVoidAsync("utilFuncs.focusElementByID", elementID))
                    .AsTask()
        }
        |> Async.AwaitTask

**Comment by Martin521** [comment]
I just use 
`let focusElement (id:string) = this.JSRuntime.InvokeVoidAsync("focusElement", id) |> ignore`.
 Why should I wait for it to complete?

**Comment by Tarmil** [comment]
This is fixed in version 0.22. An attribute `ref="MyRef"` will give you a method `.MyRef()` that takes an `HtmlRef` as argument. https://fsbolero.io/blog/20230410-bolero-0-22-released
