### ISSUE TITLE
How to make Select and option elements in HTML

### ISSUE THREAD

**Issue by Gilligan128** [fsbolero/Bolero#292]
I have tried many ways using Bolero.Html to make a select element with options in it. All break the compiler. What am I doing wrong?
Example:
```
select { 
       option {
           attr.value "0"
       }
       
       bind.change.string (string field) (changeAction)
      }
```
fails with a very unclear message about "no overloads match for method 'Combine'

**Comment by Tarmil** [comment]
Yeah, I wish there was a way to make the error clearer... The problem is that attributes must come before child elements. So you need to put the `bind` before the `option`.

**Comment by Gilligan128** [comment]
Ok thank you!
