### ISSUE TITLE
is it possible to extend Bolero HTML Builder CEs with `CustomOperation`?

### ISSUE THREAD

**Issue by BryanWilhite** [fsbolero/Bolero#302]
Looking at  “[Expanding Existing Computational Expressions](https://blog.mavnn.co.uk/expanding-existing-computational-expressions/)” suggests to me that, say, `ElementBuilder` can be extended.

Are the Bolero HTML Builder CEs open to this or do I need to learn more stuff about CEs?

instead of using function like this:

```fsharp
bulmaCardImageContainer  
    NoCssClasses  
    (imageElement  
        NoCssClasses  
        NoAttr  
        $"{feed.feedTitle} feed image"  
        (feed.feedImage |> Option.get |> Uri))
```

…we can do this:

```fsharp
bulmaCardImageContainer {
    NoCssClasses
    imageElement {
        NoCssClasses  
        NoAttr  
        $"{feed.feedTitle} feed image"  
        feed.feedImage |> Option.get |> Uri
    }
}
```

…by extending `Bolero.Html`?

**Comment by BryanWilhite** [comment]
Looks like the answer is _no_:

>...computation expressions and custom operators are two orthogonal language features that do not interact in any way...
>---[Tomas Petricek](https://stackoverflow.com/a/39980961/22944)

**Comment by granicz** [comment]
On the contrary, you should be able to augment `Bolero.Builders.ElementBuilder` with your own custom operators/keywords, following the same convention as for the built-in set. To provide type safety, i.e. where certain features are only available inside a given custom operator like in your example above, you will need extra sub-builder types and quite a bit of boilerplate code. Overall, not a whole lot of gain for a small improvement of notation, but if you do it well (with inlining, etc.) you might just make it more performant than ordinary function calls.

That said, I'd strongly advise against encoding HTML components in F# and use templating instead.

**Comment by BryanWilhite** [comment]
thanks @granicz! ... i have opened [a SO question](https://stackoverflow.com/questions/76139232/what-is-the-relationship-between-customoperationattribute-and-the-conventional) to get a better understanding of CEs

with regard to templating, i would be interested in a templating approach where we have something like haml or pug to avoid the verbosity
