### ISSUE TITLE
"SetPage" duplicated when dispatched through Cmd.ofMsg

### ISSUE THREAD

**Issue by clbrem** [fsbolero/Bolero#303]
When the router is connected to the Elmish state using `Router.infer`, routing commands issued through Cmd.ofMsg are duplicated.

Here is a minimal example (see [github](https://github.com/clbrem/bolero-issue/blob/main/src/NavigationDupe.Client/Main.fs)):

```fsharp
type Page =
    | [<EndPoint "/">] Home
    | [<EndPoint "/secondPage">] NewPage    
type Message =
    | SetPage of Page
    | DoAThing
let update message model =
   // This demonstrates which messages are duplicated  
    Console.WriteLine($"{message}")
    match message with
    | SetPage page ->
        {model with page = page}, Cmd.none
    | DoAThing ->
        model, Cmd.ofMsg (SetPage NewPage)
let router = Router.infer SetPage (fun model -> model.page)
```

When `DoAThing` is dispatched from `Home`, `SetPage NewPage` gets dispatched twice. This causes unexpected behavior whenever one wants to trigger a redirect after performing an action, i.e. create a new resource and then navigate to the corresponding view.

**Comment by clbrem** [comment]
I've found a workaround, but it is not ideal. 
```fsharp
type Message = 
| SetPage of Page
| Redirect of Page
| DoAThing

let update message model = 
  match message with
  | SetPage page -> 
     { model with page = page }, Cmd.none
  | Redirect page ->
    { model with page = page }, Cmd.none
  | DoAThing ->
    model, Cmd.ofMsg (Redirect NewPage)
let router = Router.infer SetPage (fun model -> model.page)
```
When `DoAThing` is dispatched from `Home`, `Redirect NewPage` is dispatched once, followed by `SetPage NewPage`. Any actions triggered by `SetPage NewPage` (i.e. fetching data, etc) would only be run once.

**Comment by Martin521** [comment]
I have not used routing myself, but as far as I understand it, the SetPage message is indeed not meant to be used by you, but only by the router. It is only a way to flexibly configure the router to manipulate the model in the right way.

**Comment by Tarmil** [comment]
Yeah, we can't really detect that a URL change was caused by the same message that it triggers. So it's best to avoid dispatching it directly. Instead you can either have a separate message like you did, or directly set `model with page = page` in the update for `DoAThing`.

Maybe the documentation should recommend calling this message something like `PageChanged`, to emphasize that it's not meant to be dispatched directly.

**Comment by clbrem** [comment]
> Maybe the documentation should recommend calling this message something like `PageChanged`, to emphasize that it's not meant to be dispatched directly.

This makes sense! Thanks all.

**Comment by Tarmil** [comment]
Documentation updated.
