### ISSUE TITLE
Scoped css: scope name not generated as documented

### ISSUE THREAD

**Issue by kgday** [fsbolero/Bolero#305]
If I have a component called xyz and I have a css file called xyz.bolero.css, according to the docs I should have a scopename property generated  of CssScopes.xys.  However instead we get CssScopes.``$([System.IO.Path]::GetFileName('xyz.bolero')`` I am running package version of Bolero 0.22.44.

**Comment by Tarmil** [comment]
Actually 0.22.44 should already be the fixed version... Are you also using this exact version of Bolero.Build? And if so, did you upgrade it from a previous 0.22?

**Comment by kgday** [comment]
this is the line from by fsproj file

<PackageReference Include="Bolero" Version="0.22.44" />

**Comment by kgday** [comment]
yes I did upgrade it from the previous 0.22.

**Comment by Tarmil** [comment]
Okay, I guess if a bad name was generated by the previous package, then an upgrade alone won't regenerate it. What if you modify the CSS file and then run a build, does that fix it?

**Comment by kgday** [comment]
Ah, I should have thought of that. That did the trick. Thank you.

**Comment by Tarmil** [comment]
Maybe we could include the version of Bolero.Build in the generated file name, so that an upgrade will generate a fresh file.

**Comment by Tarmil** [comment]
I just published a patch v0.22.45 that should ensure that the module is re-generated after upgrading Bolero.Build.
