### ISSUE TITLE
Plain Webassembly project template compilation fails for each new minor .NET SDK

### ISSUE THREAD

**Issue by ardave** [fsbolero/Bolero#314]
I've had a vanilla template project (created using `dotnet new bolero-app --server=false`) fail to build as new dotnet SDK minor versions are released.

In other words, a project created from template under SDK 7.0.7 failed when 7.0.8 was released.  And now today the compilation of a project working under 7.0.8 broke when 7.0.9 was released.  

No file changes on my end, nor new SDK installations on my dev machine.  Just build one day, it succeeds, go to bed, build again the next day and it fails.

I've tried pinning every version of every dependency that is pinnable, but no luck.

Also, it _does_ fix the problem to download and install the new minor SDK version, but it would be nice to not need to do this every week or two.

![image](https://github.com/fsbolero/Bolero/assets/1380588/6d579327-ba97-4010-b94f-06c4debae18e)

Thanks a bunch.

**Comment by Tarmil** [comment]
So I'm guessing your runtime was updated automatically by Windows Update, and the mismatch with the (non-updated) SDK is the issue. Do you have the build error message?

**Comment by ardave** [comment]
It looks like my latest Windows Update was ~2.5 months ago, and the dotnet CLI says that my latest version of Microsoft.AspNetCore.App is 7.0.8 aka yesterday's version, but something in the runtime dependency chain is looking for 7.0.9, aka today's version.  

My guess is that something from `<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">` on down isn't holding steady from one build to the next, but I can't figure out what.

Thanks for giving it a think!

![image](https://github.com/fsbolero/Bolero/assets/1380588/03af1ea0-bc5a-432d-9ca1-76ec53b859cf)
![image](https://github.com/fsbolero/Bolero/assets/1380588/c8bd58eb-05b6-48df-bbcf-91421cafbbf9)

**Comment by Tarmil** [comment]
I've been able to reproduce the issue. It seems that forcing the version of `Microsoft.AspNetCore.Components.WebAssembly.DevServer` to be the same as your runtime (7.0.7 in my case) helps.

**Comment by ardave** [comment]
Works like a charm - awesome!  I'm always glad when it's not "just me."  

Thanks a bunch for the help.
