### ISSUE TITLE
External JS scripts do not work inside the Bolero "program"

### ISSUE THREAD

**Issue by Gilligan128** [fsbolero/Bolero#328]
I don't know if this is Blazor or Bolero, but I have a js script I reference to do some behavior and it does not work for any html inside the Bolero Program, but works outside of it. Extremely frustrating, on the level of "I want to strip out the framework and find another path" 

Here are some snippets:

In the `Index.fs` I have this
```   
script {
                   attr.src "https://unpkg.com/hyperscript.org@0.9.11"  
            }
  ```
  
  if I put an attribute for this library outside the RootComponent/Program, like so:
  ```
      div {
                
                attr.id "main"
                div {
                      "_" => "on click call alert('this works!')"
                      "Click Me!"
                }
                
                rootComp<Main.MyApp>
            }
  ```
  That works.
  BUT, if I put an attribute INSIDE of it, say on the "home page" like so:
  ```
    <template id="Home">
                <div class="content" _="on click call alert('This doesn't work!')">
  ```
  This does not work!
  I have no idea what is going on.
  
  ANd I have tries importing the script directly into the JSRuntime after Prerender to no avail.

**Comment by Tarmil** [comment]
I guess this must be related to how hyperscript finds scripts to run, it probably looks for them on startup and therefore can't find scripts inserted dynamically by other means than itself.

After a quick search, it just doesn't seem designed to be able to do that. The only solution I found (and a very unsatisfactory one that won't play well with Blazor) is to [explicitly clone and re-insert the element in hyperscript](https://github.com/rozek/hyperscript-notes#change-or-just-reload-some-element-scripts-at-runtime).

**Comment by Gilligan128** [comment]
Ah, well. Such is life I guess. Thanks for the quick response and linked workaround!
