### ISSUE TITLE
Upgrading to .net 8.0 client wasm hosted project, compiler errors: failing 'open Bolero.Html'

### ISSUE THREAD

**Issue by kgday** [fsbolero/Bolero#330]
After upgrading the project to .net 8.0 we have a number of compile errors, one of them is the failing of 'open Bolero.Html', this of course kills everything view related.

**Comment by kgday** [comment]
I notice in the source thate while the Bolero project is targeting .net6.0 and .net8.0, the Bolero.Html project is only targeting .net6.0.

**Comment by Tarmil** [comment]
Ah right, since the Bolero.Html assembly is included in the Bolero package, rather than in a separate package, it needs all the targets.

**Comment by Tarmil** [comment]
This is now fixed in v0.23.46. (cc @xperiandri)

**Comment by psymm** [comment]
Thanks @Tarmil, but does packet.template need to be updated too so the nuget install puts Bolero.Html into lib/net8.0 ?

**Comment by Tarmil** [comment]
Ah, good catch. For some reason I misremembered how the file was included in the package and thought it was automatic.

**Comment by Tarmil** [comment]
Fixed in v0.23.49, thanks for the report!
