### ISSUE TITLE
Add Server-project retroactively?

### ISSUE THREAD

**Issue by ibrahim324** [fsbolero/Bolero#344]
This has not been discussed as far as I can tell, but is it possible to add a Server after starting with a Client?

**Comment by Tarmil** [comment]
Sure. The client project itself is pretty much the same whether there is a server behind it or not; you can just get rid of the index.html as it will be served from the server instead.

To add the server side, you can create an empty ASP.NET Core application, reference the client from it, and follow ["Configuring hosted modes"](https://fsbolero.io/docs/Hosting#configuring-hosted-modes) from the documentation.
