### ISSUE TITLE
A function labeled with the 'EntryPointAttribute' attribute must be the last declaration in the last file in the compilation sequence.

### ISSUE THREAD

**Issue by xperiandri** [fsbolero/Bolero#35]
Why could I get `Startup.fs(35,9): error FS0433: A function labeled with the 'EntryPointAttribute' attribute must be the last declaration in the last file in the compilation sequence.`?

**Comment by weebs** [comment]
In the Startup.fs of both the Client and Server project, the function labeled with `[<EntryPoint>]` needs to be last in the file

**Comment by weebs** [comment]
Oops misread the error

In your fsproj file, the F# file that contains the `[<EntryPoint>]` attribute needs to be last in the list of included files

**Comment by xperiandri** [comment]
Ah, I got it
https://stackoverflow.com/questions/51622669/f-docker-application-a-function-labeled-with-the-entrypointattribute-attribu
