### ISSUE TITLE
Web worker with F#

### ISSUE THREAD

**Issue by kaashyapan** [fsbolero/Bolero#350]
There are a couple of libs which seem to enable compiling C# code to run as a web worker
https://github.com/Tewr/BlazorWorker
https://github.com/LostBeard/SpawnDev.BlazorJS

Is it possible to have a similar arrangement with F# ? 
Would it possible where was a JS web application that can offload CPU intensive activities to a F# web worker? The C# libs dont seem to allow that.

**Comment by Tarmil** [comment]
I would expect these libs to work with F# just the same as they do with C#.

**Comment by Martin521** [comment]
I tried SpawnDev.BlazorJS some time ago, you can find a demo project [here](https://github.com/Martin521/BoleroWebworkerDemo).
In the end, however, I never used it for larger applications as I hit too many limitations.

**Comment by kaashyapan** [comment]
Thanks.
