### ISSUE TITLE
How build reusable Bolero components in a separate assembly

### ISSUE THREAD

**Issue by fwaris** [fsbolero/Bolero#363]
I want isolate parts of my UI application into separate DLLs.

When I use Bolero reference in a plain .Net assembly (i.e. not Microsoft.NET.Sdk.BlazorWebAssembly), 

I get the following error at build time:

```
The target "ResolveScopedCssInputs" does not exist in the project.
```

Build error goes away when I use Microsoft.NET.Sdk.BlazorWebAssembly but then I can't reference this Project into the main UI project because both have this SDK.

Is there a quick solution to this problem?

**Comment by Tarmil** [comment]
Looking at some component libraries on GitHub, they use the SDK `Microsoft.NET.Sdk.Razor` ([for example](https://github.com/microsoft/fluentui-blazor/blob/dev/src/Core/Microsoft.FluentUI.AspNetCore.Components.csproj)), so I think that's what needs to be used here too.

**Comment by fwaris** [comment]
thanks! I will check it out
