### ISSUE TITLE
Update to Blazor 0.8

### ISSUE THREAD

**Issue by OnurGumus** [fsbolero/Bolero#38]
Can  we have a version  that uses Blazor v 0.8 ?

**Comment by ctaggart** [comment]
It looks like everything after 0.7.0 is marked as pre-release. All the new templates are build to use `0.9.0-preview3-19154-02`. Do you really want 0.8 or the latest?

``` xml
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Blazor" Version="0.9.0-preview3-19154-02" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Build" Version="0.9.0-preview3-19154-02" PrivateAssets="all" />
  </ItemGroup>
```

https://www.nuget.org/packages/Microsoft.AspNetCore.Blazor

**Comment by OnurGumus** [comment]
That's a good question. However currently official release of Blazor even if it is marked is preview is 0.8. If you ask my opinion, Since both blazor and bolero are experimental, I would target the latest releases, even use .net core 3.0 instead. So when few months after when .net core 3.0 is up, bolero will be up to date.

**Comment by Tarmil** [comment]
Yeah we don't want to wait for .net core 3.0 to be released to upgrade. We'll probably go straight to 0.9.

**Comment by granicz** [comment]
Agreed, no point in waiting.

**Comment by ctaggart** [comment]
Today, the first 
https://github.com/aspnet/Blazor/releases/tag/3.0.0-preview4
https://devblogs.microsoft.com/aspnet/blazor-now-in-official-preview/
* .NET Core 3.0 Preview 4 SDK (3.0.100-preview4-011223) will need to be used
* The Blazor version is 3.0.0-preview4-19216-03
* `dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.0.0-preview4-19216-03` will be helpful when looking at the dependency updates

It may be difficult to stay up-to-date with the changes. I think #43 will help.

**Comment by Tarmil** [comment]
Yes, this 3.0 preview is great news! Time to update Bolero ASAP.

I'll still try to update using paket though, but if it becomes frustrating then your PR will be welcome.

**Comment by granicz** [comment]
I had a quick look at the PR and it looks pretty solid. @Tarmil How is your update with paket going?

**Comment by Tarmil** [comment]
I have a first attempt on the blazor-3.0 branch. Some tests fail, and template hot reload is #if'd out because Blazor.Extensions.SignalR is not yet updated for 3.0, but it's a start. Paket hasn't been too much of an obstacle TBH.

**Comment by OnurGumus** [comment]
How do we build 3.0 branch? build.cmd fails with various errors.

**Comment by Tarmil** [comment]
It should just build. Do you have the dotnet SDK 3.0.100-preview4 installed?

**Comment by OnurGumus** [comment]
Yes, right now when I build 3.0 branch it fails with below error:
```
C:\Program Files\dotnet\sdk\3.0.100-preview4-011223\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(145,5): error MSB4018: System.ArgumentException: '0.5.0-' is not a valid version string. [C:\Users\Onur.Gumus\Downloads\Bolero-blazor-3.0\Bolero-blazor-3.0\src\Bolero.Build\Bolero.Build.csproj]
```

**Comment by Tarmil** [comment]
@OnurGumus This looks like an issue with nbgv, the tool that generates the version number. Does running `.paket/nbgv get-version -v SemVer2` also give `0.5.0-` as output?

@ctaggart Is this a behavior you've ever observed with nbgv? Note that I've [added some code](https://github.com/fsbolero/Bolero/commit/d6d783bac84173b435422f584f128a513b2ac04e) that calls it locally, not just on AppVeyor.

**Comment by ctaggart** [comment]
No problems builds for me locally. I'm not using `3.0.0-preview5-27626-15`. nbgv works as expected:
```
PS C:\Users\taggac\github\Bolero> .paket/nbgv get-version -v SemVer2
0.5.12-3cc4685
```
It is probably good to upgraded to 2.3.151, which supports a computer with dotnet 3 and no dotnet 2. I added the [dotnet 3 support](https://github.com/AArnott/Nerdbank.GitVersioning/pull/326#issuecomment-490928205).

**Comment by Tarmil** [comment]
Thanks, I've updated my 3.0 branch to use 2.3.151.

**Comment by ctaggart** [comment]
I think this issue can be closed by https://github.com/fsbolero/Bolero/pull/46 just being merged.
