### ISSUE TITLE
minimal=true server=false simple view displays nothing

### ISSUE THREAD

**Issue by markfirmware** [fsbolero/Bolero#40]
Changing a fresh bolero-app with just

    let view model dispatch =
        text “test”

does not display anything. This is a likely scenario (it was the first thing I tried.)

Regards,
Mark

**Comment by Tarmil** [comment]
Oh wow, somehow I didn't realize that `type Model = unit` doesn't work. The fact that `()` represented as `null` probably has to do with this. If you just change the `Model` type to something more concrete like a record, it will work.

Thanks for the report, I'll fix the project template ASAP.

**Comment by Tarmil** [comment]
Moving this issue to https://github.com/fsbolero/Template/issues/8.
