### ISSUE TITLE
How do I add css elements?

### ISSUE THREAD

**Issue by markfirmware** [fsbolero/Bolero#42]
I know how to use styles with attr.style but I don’t know how to define keyframes such as:

    @keyframes fade { 0% { background-color: white } 100% { background-color: red } }

**Comment by Tarmil** [comment]
I would advise defining these statically, either in a `<style>` tag in `index.html`, or in a separate .css file with a corresponding `<link>` in `index.html`. But if you really want to define it within Bolero, then a style tag should work:

```fsharp
let myElement =
    concat [
        style [] [text "@keyframes fade ..."]
        div [attr.style "animation-name: fade"] [text "content..."]
    ]
```

**Comment by markfirmware** [comment]
Thank you. Both approaches work fine.
