### ISSUE TITLE
Compatibility layer for Blazor server-side hosting

### ISSUE THREAD

**Issue by ijsgaus** [fsbolero/Bolero#44]

**Comment by Tarmil** [comment]
Are you having specific issues with server-side hosting right now?

**Comment by panesofglass** [comment]
How do you change the Bolero template to use the server-side Blazor support?

**Comment by Tarmil** [comment]
@panesofglass There's nothing Bolero-specific to do, so the steps are the same as for a plain Blazor project:

1. In `wwwroot/index.html`, replace `blazor.webassembly.js` with `blazor.server.js`;
2. In the server-side `Startup`:
    1. In `ConfigureServices`, add `services.AddServerSideBlazor<YourClient.Startup>() |> ignore`;
    2. In `Configure`, replace `UseBlazor` with `UseServerSideBlazor`.

**Comment by panesofglass** [comment]
Thanks!

**Comment by jam40jeff** [comment]
Would a compatibility layer be needed to make remoting work transparently?

**Comment by Tarmil** [comment]
It already works transparently: when running on the server, "remote" calls invoke the function directly without going through the network.

**Comment by jam40jeff** [comment]
Sorry, I should have been more specific.  I see that the functions calls are invoked directly, which is great.  However, `null` is passed to the `HttpContext` parameter of the functions for `Remote.withContext` and `Remote.authorize` in the app that gets created with the template causing it to crash with a `NullReferenceException`.  Is there a way to capture and send along this information so it is available just as it is when running on the client side?

**Comment by Tarmil** [comment]
Ah, right, indeed the HttpContext isn't handled. I guess authentication should just work using the long-running context from SignalR, but I need to test to make sure.

**Comment by rusanov-vladimir** [comment]
Out of box server side rendering from template doesn't seem to work. Server acts as API backend, but I'm unable to debug client side F# using it.
I've tried to change it according to suggestions above, but it also doesn't work. It looks like `UseServerSideBlazor` is [removed in Blazor](https://github.com/aspnet/AspNetCore/commit/2d9cba86fd304777ba27a54620a8d315f58d3602). I'm able to configure SignalR via `UseEndpoints(fun e -> e.MapBlazorHub())`, but I can't find a way to express this without using razor and keeping fable style HTML: `<app>@(await Html.RenderComponentAsync<App>())</app>`. 
Maybe I'm misunderstanding the idea about server side and bolero doesn't support server-side rendering at all?

**Comment by rusanov-vladimir** [comment]
Opened a more specific issue #52 regarding what I was asking here.

**Comment by jam40jeff** [comment]
I don't believe `UseServerSideBlazor` was removed.  The link you provided does not indicate that in the diff.  Also, it is mentioned in this MS blog article from June 4, 2019.

https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-3.0

**Comment by rusanov-vladimir** [comment]
@jam40jeff well, probably you are just using the older version. Just searching code by `UseServerSideBlazor` [yeilds 0 results](https://github.com/aspnet/AspNetCore/search?q=UseServerSideBlazor&type=Code).
The latest version within Bolero repository isn't [using it anymore also](https://github.com/fsbolero/Bolero/blob/master/tests/Server/Startup.fs):

**Comment by jam40jeff** [comment]
Interesting.  So it seems that Blazor server side has become part of ASP.NET Core 3.0 (called Razor Components now).  They seem to have changed the API significantly.  When you run the Bolero sample you referenced, does debugging the client rendering code not work anymore?

**Comment by rusanov-vladimir** [comment]
Yes, indeed it changed somewhat. If I run pure blazor server side hosting it works as expected and I'm able to debug client side. When I tried the Server project that is inside the bolero repository it just returns 404.

**Comment by OnurGumus** [comment]
> Ah, right, indeed the HttpContext isn't handled. I guess authentication should just work using the long-running context from SignalR, but I need to test to make sure.

Regarding above what is the recommended approach to access HttpContext for server side scenarios?

**Comment by Tarmil** [comment]
HttpContext is now accessible when running in server-side mode. If there are other specific issues with running Bolero in server-side mode, please create a dedicated issue, thanks!

**Comment by panesofglass** [comment]
@Tarmil do you have a sample demonstrating this?

**Comment by panesofglass** [comment]
Looks like the solution now is to change the `defaultIsServer` parameter in `HostModel` to `true`.
