### ISSUE TITLE
Server side hosting doesn't work

### ISSUE THREAD

**Issue by rusanov-vladimir** [fsbolero/Bolero#52]
I want to have a way to debug client side code using server side hosting of Blazor.

https://github.com/fsbolero/Bolero/tree/master/tests/Server seems to be doing the setup I'm looking for, but unfortunately it doesn't work.

I've built the project and run Server.exe. Navigated to http://localhost:5000 and I'm getting HTTP 404 which I also see in the log: 

```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'Fallback {*path:nonfile}'
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'Fallback {*path:nonfile}'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 0.7887000000000001ms 404
```

P.S. Remoting.Server seems to be working fine.

**Comment by Tarmil** [comment]
Oh indeed. Running Server with `dotnet run` works fine, but starting the exe directly returns 404. This needs investigating.

> P.S. Remoting.Server seems to be working fine.

Remoting.Server is a server host that runs a client-side Blazor app, so it's not surprising that it has a different behavior.

**Comment by Tarmil** [comment]
Ah, got it: you need to make sure that you're running from the project folder (`tests/Server/`), because `MapFallbackToFile` looks for `index.html` in the working directory.

I guess `dotnet run` runs the exe from that folder even if you run `dotnet run` from elsewhere, so it always works.

**Comment by rusanov-vladimir** [comment]
Ah, damn, running it from `tests/Server/` indeed solves the issue! Thanks a million!
