### ISSUE TITLE
Update to .NET Core 3.0-preview6

### ISSUE THREAD

**Issue by OnurGumus** [fsbolero/Bolero#59]
with .net core 3.0 preview 6 , I am getting below error:
```
Application startup exception: System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Authorization.IAuthorizeData' from assembly 'Microsoft.AspNetCore.Http.Abstractions, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Bolero.Remoting.Server.Remote.authorize[req,resp](FSharpFunc`2 f)
   at HelloWorld.Server.BookService.get_Handler() in D:\playground\bolero2\HelloWorld\src\HelloWorld.Server\Startup.fs:line 26
   at Bolero.Remoting.Server.RemoteHandler`1.Bolero-Remoting-Server-IRemoteHandler-get_Handler()
   at <StartupCode$Bolero-Server>.$Remoting.AddRemoting@235-1.Invoke(IServiceProvider services)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSit
```

**Comment by ScottHutchinson** [comment]
I can confirm that for me preview 6 failed, but preview 5 works great so far. The hot reload is amazing!

**Comment by Tarmil** [comment]
This depends on the Blazor SignalR extension to be updated for preview6, see https://github.com/BlazorExtensions/SignalR/issues/32.

**Comment by ScottHutchinson** [comment]
It's still broken. I guess it hasn't been deployed yet? If so, maybe we should not close an issue until the solution has been deployed? How could I check the Blazor version that is installed? Thanks

**Comment by Tarmil** [comment]
It is merged to master, which is why I closed the issue. You can try the nightly build by adding the CI to your NuGet sources: https://ci.appveyor.com/nuget/bolero

**Comment by ScottHutchinson** [comment]
@Tarmil Thanks. I will try to learn how to use the nightly build. But how will I know when `dotnet new -i Bolero.Templates` will work with preview6, so I can tell my colleagues "you can use it with preview6 now, and you don't need to downgrade .NET Core 3.0, or use a nightly build anymore"?

**Comment by granicz** [comment]
@ScottHutchinson It will have a "released: vx.xx" tag, such as [this ticket](https://github.com/fsbolero/Bolero/issues/38).

**Comment by ScottHutchinson** [comment]
@granicz That helps. I wonder if I'm subscribed to this closed issue, will I get notified when that released label gets added?

Also, I guess I could subscribe some RSS reader to https://www.nuget.org/packages/Bolero.Server/atom.xml to get notifications of releases. It would be nice if the Nuget Gallery had that built in, but I don't see it now.

**Comment by ScottHutchinson** [comment]
> It is merged to master, which is why I closed the issue. You can try the nightly build by adding the CI to your NuGet sources: https://ci.appveyor.com/nuget/bolero

I added that url to a nuget.config file in my HelloWorldBolero repo root folder and ran dotnet restore. But it didn't seem to change anything.
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="MyGet" value="https://ci.appveyor.com/nuget/bolero" />
  </packageSources>
</configuration>
```
Do I need to put that nuget.config file in each project folder (client and server)?

Maybe I need to update my PackageReference elements?

`<PackageReference Include="Bolero.Build" Version="0.5.28-preview*" />`
