### ISSUE TITLE
Routing: support query arguments

### ISSUE THREAD

**Issue by Tarmil** [fsbolero/Bolero#6]
Add support for parsing query arguments in the router. Potential syntax (inspired by WebSharper's):

```fsharp
type Page =
    | [<EndPoint "/foo"; Query("x", "y")>]
      Foo of pathArg: string * x: int * y: option<string>
```

**Comment by kaashyapan** [comment]
Thanks for this project.
Is there is something blocking this ?

Is it possible to parse incoming query parameters in Bolero today ?
I saw that you have used the js window api in TryFsharpOnWasm project.
Is that still the only way to do this ?

It appears that the NavigationManager is available via DI by default but I wasnt able to get it to work.

https://docs.microsoft.com/en-us/aspnet/core/blazor/dependency-injection?view=aspnetcore-3.1
https://docs.microsoft.com/en-us/aspnet/core/blazor/routing?view=aspnetcore-3.1#uri-and-navigation-state-helpers
