### ISSUE TITLE
Split off the templating hot reload to a separate repository

### ISSUE THREAD

**Issue by Tarmil** [fsbolero/Bolero#63]
Right now, this repository depends on Blazor.Extensions.SignalR to build, which is annoying because whenever there's a new Blazor version (as is currently the case with 3.0-preview6), we need to wait for B.E.SignalR to update to it before we can do anything. Since it's only used by the templating hot reload, splitting it off would make upgrading easier.

This means that we would potentially release versions of Bolero without a corresponding version of Bolero.HotReload (yet), but since the dependency of HotReload on Bolero is strict, it won't cause breakage for users. People who use HotReload just won't be able to update to the next Bolero until HotReload is updated.

**Comment by Tarmil** [comment]
This does mean reintroducing a package `Bolero.HotReload.Server` though.

**Comment by granicz** [comment]
I do like the hot reload functionality as a separate component, makes it easier to enhance.
