### ISSUE TITLE
Error trying to compile

### ISSUE THREAD

**Issue by rodrigodevelms** [fsbolero/Bolero#67]
![to](https://user-images.githubusercontent.com/41160178/62424238-1086cf80-b69a-11e9-8938-f54b6f72421c.png)

**Comment by Tarmil** [comment]
It seems that this is caused by inconsistent FSharp.Core references because of https://github.com/fsbolero/Templating.HotReload/issues/2. Can you update to Bolero.HotReload 0.7.2 and check that it fixes this issue?

**Comment by rodrigodevelms** [comment]
Client compiles. But the server has the following error:
![Error](https://user-images.githubusercontent.com/41160178/62827762-536a0b00-bba4-11e9-8570-1808f05e957a.png)

**Comment by Tarmil** [comment]
That's odd, I don't know why is it looking for a .exe; it's a .dll.
