### ISSUE TITLE
asp.net core preview 8 update issues

### ISSUE THREAD

**Issue by OnurGumus** [fsbolero/Bolero#69]
The updates that affect bolero as below:
- Update Microsoft.AspNetCore.* package references to 3.0.0-preview8.19405.7.
- In Razor components rename OnInit to OnInitialized and OnInitAsync to OnInitializedAsync.
- Rename ElementRef to ElementReference.
- Update calls to ComponentBase.Invoke to call ComponentBase.InvokeAsync.

The full list is here:
https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-8/

I tried above changes but the template provider fails with
Errors like:

```
C:\Users\Onur.Gumus\source\repos\Bolero2\tests\Client\Main.fs(132,25): error FS0041: No overloads match for method 'Kind'. The available overloads are shown below.
3>C:\Users\Onur.Gumus\source\repos\Bolero2\tests\Client\Main.fs(143,25): error FS0001: This expression was expected to have type    'Bolero.Node (Bolero, Version=0.7.0.0, Culture=neutral, PublicKeyToken=null)'    but here has type    'Bolero.Node (Bolero.Templating.Provider, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null)'
6>C:\Users\Onur.Gumus\source\repos\Bolero2\tests\Unit.Client\Html.fs(166,9): error FS0001: All elements of a list must be of the same type as the first element, which here is 'Bolero.Node (Bolero, Version=0.7.0.0, Culture=neutral, PublicKeyToken=null)'. This element has type 'Bolero.Node (Bolero.Templating.Provider, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null)'.
3>C:\Users\Onur.Gumus\source\repo
```

And I got stuck here.

**Comment by Tarmil** [comment]
Thanks for the effort! I tried reproducing your issue, but actually after applying the same changes I was able to build and run the tests just fine. Maybe you had an issue with old artifacts still being loaded? Can you try running `dotnet build-server shutdown` then compiling again, to see if that fixes it?

**Comment by OnurGumus** [comment]
I did, it did not fix it. I have also cleaned up obj and bin folders. It did not help.

**Comment by OnurGumus** [comment]
I think I found the issue. Something has edited the bolero.fsproj file (as in changing places of things). I am not sure what it was. Reverting the changes to the proj file has fixed the issue.

**Comment by OnurGumus** [comment]
@Tarmil  I also noticed one more difference.
I had to add the folowing line to paket.template line in Bolero project
 bin/Release/typeproviders/fsharp41/netstandard2.0/Microsoft.AspNetCore.Components.Web.dll ==> typeproviders/fsharp41/netstandard2.0

Otherwise the type provider complains about it could not load Microsoft.AspNetCore.Components.Web.

**Comment by OnurGumus** [comment]
And even after that when I create my own project it fails with 
1>Unhandled Exception: Mono.Linker.MarkException: Error processing method: 'System.Type Bolero.Templating.Parsing/HoleTypeModule::EventArg(System.String)' in assembly: 'Bolero.Templating.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve Microsoft.AspNetCore.Components.UIFocusEventArgs

**Comment by OnurGumus** [comment]
Yeah, they have moved these types from Microsoft.AspNetCore.Components to Microsoft.AspNetCore.Components.Web, so another breaking change. Though I don't know how to tackle it.

**Comment by OnurGumus** [comment]
I don't think there is a solution
There is no new version for `Microsoft.AspNetCore.Components.Browser` and it still uses `UIEventArgs` from the `Microsoft.AspNetCore.Components`

This eventually causes Templating.HotReload tests to fail once you upgrade to Preview8

**Comment by OnurGumus** [comment]
Ok after more digging, I learnt that **Microsoft.AspNetCore.Components.Browser** has been obsoleted and the new library is **Microsoft.AspNetCore.Components.Browser.Web**
As a result **Blazor.Extensions.SignalR** package must be upgraded 0.3.0. Then everything seems working fine.

**Comment by xperiandri** [comment]
![image](https://user-images.githubusercontent.com/2365592/63374427-7a89bf00-c392-11e9-9218-f497e236a827.png)

``` F#
// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
member this.Configure(app: IApplicationBuilder, env: IWebHostEnvironment) =
	app
		.UseAuthentication()
		.UseRemoting()
		.UseClientSideBlazorFiles<Client.Startup>()
		.UseRouting()
		.UseEndpoints(fun endpoints ->
#if DEBUG
			endpoints.UseHotReload()
#endif
			endpoints.MapDefaultControllerRoute() |> ignore
			endpoints.MapFallbackToClientSideBlazor<Client.Startup>("index.html") |> ignore)
	|> ignore
```

Why could this happen?

**Comment by xperiandri** [comment]
And if I roll back `UseHotReload` call to app instance I've got `Could not find method "EndInvokeJS" on type "Mono.WebAssembly.Interop.MonoWebAssemblyJSRuntime"` in browser

**Comment by Tarmil** [comment]
@xperiandri This is because Bolero.HotReload itself needs to be updated to preview8, as some APIs it relies on have been changed. I'm working on it 🙂
