### ISSUE TITLE
Add bind.radio

### ISSUE THREAD

**Issue by Tarmil** [fsbolero/Bolero#75]
For radio button groups.

```fsharp
module bind =
    val radio : group:string -> thisButtonValue:string -> onChecked:(unit -> unit) -> Attr

// Example use:
let myRadioList model dispatch =
    forEach {1..10} <| fun ix ->
        input [
            bind.radio "mygroup" (string ix) (fun () -> dispatch (SetMyGroup ix))
        ]

// Equivalent to:
let myRadioList model dispatch =
    forEach {1..10} <| fun ix ->
        input [
            attr.``type`` "radio"
            attr.name "mygroup"
            attr.value (string ix)
            on.change (fun args ->
                if (args.Value :?> string) = string ix then
                    dispatch (SetMyGroup ix))
        ]
```

**Comment by Tarmil** [comment]
It turns out that the following is sufficient:

```fsharp
let myRadioList model dispatch =
    forEach {1..10} <| fun ix ->
        input [
            attr.``type`` "radio"
            attr.name "mygroup"
            bind.change (string ix) (fun _ -> dispatch (SetMyGroup ix))
        ]
```

So I think we don't actually need a separate `bind.radio` function; users can write the above to create a radio button. Similarly to how `bind.changeInt` and family don't implicitly add `attr.``type`` "number"`.

We should document this though.

**Comment by Tarmil** [comment]
[Documentation added.](https://github.com/fsbolero/website/commit/92eca81e99605f7bf92f611424a33edb107f2f1f)

**Comment by Morranr** [comment]
The HTML templates documentation page (Templating.md) still shows the note about radio buttons not being supported, which I assume should be updated similar to the Writing HTML page (HTML.md) in the above referenced commit.

**Comment by Tarmil** [comment]
Good catch! I believe we should also make it so that `bind="${Name}"` defaults to `onchange` for `type="radio"`.
