### ISSUE TITLE
Any possibilities to import elmish app into blazor?

### ISSUE THREAD

**Issue by OnurGumus** [fsbolero/Bolero#84]
I was thinking if we can import the elmish app into a c# blazor app. Ideally, it should be possible since bolero is essentially a component. When I tried, without adding bolero.dll it doesn't see the component, and when I added bolero.dll , the compilation simply bails out telling RenderTreeBuilder is not found. Perhaps it is due to a version mismatch. I was thinking perhaps someone with more skills/time can give it a shot to it.

**Comment by Tarmil** [comment]
Sounds like it might be a version mismatch indeed. What exact version of Blazor are you using?

**Comment by OnurGumus** [comment]
@Tarmil  I was trying 3.1. Actually failed with 3.0 as well. As for 3.1, create a 3.1 project and install bolero nuget package and it fails with 

```
NU1608: Detected package version outside of dependency constraint: Bolero 0.9.3-preview9 requires Microsoft.AspNetCore.Blazor (= 3.0.0-preview9.19465.2) but version Microsoft.AspNetCore.Blazor 3.1.0-preview1.19508.20 was resolved.
NU1605: Detected package downgrade: FSharp.Core from 4.5.2 to 4.5.0. Reference the package directly from the project to select a different version. 
 BlazorApp4.Client -> Bolero 0.9.3-preview9 -> Elmish 2.0.0 -> FSharp.Core (>= 4.5.2) 
 BlazorApp4.Client -> Bolero 0.9.3-preview9 -> FSharp.Core (>= 4.5.0)

```

When I tried with a 3.0 project, it fails as below

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1605	Detected package downgrade: FSharp.Core from 4.5.2 to 4.5.0. Reference the package directly from the project to select a different version. 
 BlazorApp5 -> Bolero 0.9.3-preview9 -> Elmish 2.0.0 -> FSharp.Core (>= 4.5.2) 
 BlazorApp5 -> Bolero 0.9.3-preview9 -> FSharp.Core (>= 4.5.0)	BlazorApp5	
```

**Comment by OnurGumus** [comment]
Ok I made a sample working. I created an FSharp class library for .net standard and added the bolero package to it.

**Comment by OnurGumus** [comment]
As for further updates, html templates, remoting  , and routing works within an asp.net core blazor page.

**Comment by OnurGumus** [comment]
ok nightlies work with 3.1 as well.
