### ISSUE TITLE
does hot reloading work with server mode?

### ISSUE THREAD

**Issue by OnurGumus** [fsbolero/Bolero#86]
I tried hot reloading on server mode. My initial finding is it doesn't work. Is this expected?

**Comment by OnurGumus** [comment]
I confirm it works. One just shouldn't include wwwroot unlike the docs.

**Comment by xperiandri** [comment]
> One just shouldn't include wwwroot unlike the docs.

What do you mean?

**Comment by OnurGumus** [comment]
@xperiandri, sorry for being not clear but I totally don't remember what I meant :(
