### ISSUE TITLE
Slow rendering

### ISSUE THREAD

**Issue by ptupitsyn** [fsbolero/Bolero#91]
I'm trying to implement a simple logic game in F#/Bolero. Game board is represented by a 30 * 30 html table. Table cells can have background and/or single char in them, nothing fancy.

Source: https://github.com/ptupitsyn/klopodavka-fs
Try it: https://klopodavka.netlify.com/ (click on cells with dots in them)

Clicking on a valid cell changes it's state. Handling the click takes ~35 ms on i7-9700k, which is tolerable, but on older hardware and on mobile it can take over a second, which is unusable.

* I tried profiling in Chrome, but the whole call tree consists of `wasm-function`
* I am sure it is the Bolero rendering, not the underlying game logic - if I render 5 rows of 30, it is ~6 times faster

I am new to F# and Bolero, so questions are:
* Am I doing something wrong?
* Is it possible to profile and see actual function names?

![image](https://user-images.githubusercontent.com/10922892/68122972-bc032280-ff1c-11e9-8359-b66887bef4f2.png)

![image](https://user-images.githubusercontent.com/10922892/68123013-ddfca500-ff1c-11e9-9d08-e7cc42d274b3.png)

**Comment by OnurGumus** [comment]
@ptupitsyn Perhaps you can wrap each td into an elmish component and control the rendering. Because it seams you are rerendering 900 cells for each click which is an ouch! It is documented in bolero docs how to wrap it to an elmish component.

**Comment by Tarmil** [comment]
Yes, you should wrap them in a component and override `this.ShouldRender(oldModel, newModel)` to ensure that it doesn't get re-rendered unnecessarily.

Also, collections of items like this should use the `key` attribute to help the renderer. Unfortunately this is not possible yet with `ecomp` (see #87) with the released package, but it's fixed on master and I'll do a release soon 🙂

**Comment by ptupitsyn** [comment]
@OnurGumus @Tarmil thank you, missed that part of the docs, now I'm on the right path :)

**Comment by ptupitsyn** [comment]
@Tarmil where can I read more about the `key` attr?

**Comment by Tarmil** [comment]
@ptupitsyn It corresponds to the `@key` attribute in Blazor, you can read about it [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#use-key-to-control-the-preservation-of-elements-and-components).

But actually, coming back to your specific case, I think it's better *not* to use it here. It optimizes insertions, deletions and reorderings, but in the case of a game board you're not doing any of these things.
