### ISSUE TITLE
Bolero.HotReload 0.10.1-preview9 depends on Bolero (>= 0.11.1-preview9) which doesn't exist on NuGet yet?

### ISSUE THREAD

**Issue by nodakai** [fsbolero/Bolero#92]
https://www.nuget.org/packages/Bolero.HotReload/0.10.1-preview9
https://www.nuget.org/packages/Bolero/

Is this really intentional?

**Comment by Tarmil** [comment]
Ouch, no this is not intentional, sorry. It should depend on 0.10. Let me fix this.

**Comment by Tarmil** [comment]
This is fixed in version 0.10.4-preview9.
