### ISSUE TITLE
How to do preventDefault?

### ISSUE THREAD

**Issue by OnurGumus** [fsbolero/Bolero#97]
Title says all.

**Comment by Tarmil** [comment]
[They added it in Blazor 3.1-preview](https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-core-3-1-preview-2/), so we'll need to add a corresponding function in Bolero. I haven't yet looked at what the Razor attribute becomes when compiled to C#.

**Comment by OnurGumus** [comment]
I also noticed it's not possible to return false as the event handlers are action of eventargs.

**Comment by Tarmil** [comment]
Yeah unfortunately I doubt this will ever be possible because event handlers are invoked asynchronously.

**Comment by OnurGumus** [comment]
Fixed with 0.11

**Comment by PythonSmith** [comment]
Can the preventDefault be used in HTML templates?

**Comment by Tarmil** [comment]
@PythonSmith You can use `attr="${Foo}"` in the template, and then pass `.Foo(on.preventDefault "click" true)` for example in F#.

**Comment by PythonSmith** [comment]
Thanks for the quick response.
I could not manage to get it working:
```html
<template id="TestPage">
           <a href="https://github.com" attr="${Foo}">Test</a>
</template>
```
```fsharp
let managePage model dispatch =
    Main.TestPage().Foo(on.preventDefault "oncontextmenu" true).Elt()
```
Its still clickable and redirecting me to GitHub.
I'm using Bolero v0.16.27

**Comment by Tarmil** [comment]
You need the event name without the "on" prefix, so "contextmenu".

**Comment by PythonSmith** [comment]
Sorry the example above was wrong.
But I finally found out why my oncontextmenu snippets did not work: I did not attach any callback to the contextmenu-event.
I still think its some kind of bug.
When no callback is attached to any oncontextmenu, the _on.preventDefault_ is ignored.
However if any callback is registered it works as expected.

This will not prevent the default context menu to pop up:
```html
<template id="SomeSimpleTemplate">
    <div attr="${Attr}">
        <a href="https://github.com">GitHub</a>
    </div>
</template>
```
```fsharp
div [] [
    Main.SomeSimpleTemplate().Attr(on.preventDefault "oncontextmenu" true).Elt();
]
```
This two examples will prevent it: 
```html
<template id="SomeSimpleTemplate">
    <div attr="${Attr}">
        <a href="https://github.com">GitHub</a>
    </div>
</template>
```
```fsharp
div [ on.contextmenu (fun _ -> ()) ] [
    Main.SomeSimpleTemplate().Attr(on.preventDefault "oncontextmenu" true).Elt();
]
```
and
```fsharp
div [ ] [
    Main.SomeSimpleTemplate().Attr(on.contextmenu (fun _ -> printfn "test")).Elt(); // Will show default menu
    Main.SomeSimpleTemplate().Attr(on.preventDefault "oncontextmenu" true).Elt(); // The above node makes the preventDefault work
]
```
