### ISSUE TITLE
Best way to run javascript after rendering

### ISSUE THREAD

**Issue by OnurGumus** [fsbolero/Bolero#98]
I am trying to run particular JavaScript when "AfterPreRendering" occurs however  I couldn't find a way to hook it into elmish after prerendering finishies. Any suggestions?

**Comment by OnurGumus** [comment]
I only come up with below hacky idea:
```

type MyApp() =
    inherit ProgramComponent<Model, Message>()
    let  mutable HitCount = 0
    let dispatch = 
        typeof<MyApp>
            .GetProperty("Dispatch", Reflection.BindingFlags.Instance ||| Reflection.BindingFlags.NonPublic)

    override this.OnAfterRenderAsync(firstRender) =
        HitCount <- HitCount + 1
        let res = base.OnAfterRenderAsync(firstRender)
        let d : (Message -> unit) = downcast dispatch.GetValue(this)
        if HitCount = 2 then
           Rendered |> d |> ignore
        res
```

**Comment by Tarmil** [comment]
If I'm not mistaken, `firstRender` is the condition you need. It is true after the first interactive render, ie the first render excluding server-side prerender, if any.

Regarding the call to `dispatch`, this should definitely be improved. I think I can add an abstract method that either takes `dispatch` as argument or returns a `Cmd<'msg>`.

**Comment by OnurGumus** [comment]
The firstRender = false doesn't work on client side version.  I tried and it was failing, can't remember what was happening though. 

I have come up with a much neater solution using withSubscription. That works in all scenarios. All I do is to handle Rendered message change a model state bool property like IsRendered. Once that is true, I am safely able to execute the js.

```
type MyApp() =
    inherit ProgramComponent<Model, Message>()
    override this.Program =
        let remote = this.Remote<PizzaService>()
        let update = update  remote (this.JSRuntime)
        let router = router remote
        Program.mkProgram (fun _ -> init) (update) (view  this.JSRuntime) 
        |> Program.withRouter router
        |> Program.withSubscription (fun _ -> Rendered |> Cmd.ofMsg)
```

**Comment by Tarmil** [comment]
I would have expected `firstRender = true` to work, actually.

`withSubscription` looks like a good solution in your case, provided that the button is part of the initial render of the program and not added later via eg `cond`.
